// This file was auto-generated by Fern from our API Definition.

export const FindWorkspaceUsersRequestMemberships = {
    All: "ALL",
    None: "NONE",
    Workspace: "WORKSPACE",
    Project: "PROJECT",
    Usergroup: "USERGROUP",
} as const;
export type FindWorkspaceUsersRequestMemberships =
    (typeof FindWorkspaceUsersRequestMemberships)[keyof typeof FindWorkspaceUsersRequestMemberships];
