// This file was auto-generated by Fern from our API Definition.

export const FindUserTeamManagersRequestSortOrder = {
    Ascending: "ASCENDING",
    Descending: "DESCENDING",
} as const;
export type FindUserTeamManagersRequestSortOrder =
    (typeof FindUserTeamManagersRequestSortOrder)[keyof typeof FindUserTeamManagersRequestSortOrder];
