// This file was auto-generated by Fern from our API Definition.

export const FindUserTeamManagersRequestSortColumn = {
    Id: "ID",
    Email: "EMAIL",
    Name: "NAME",
    NameLowercase: "NAME_LOWERCASE",
    Access: "ACCESS",
    Hourlyrate: "HOURLYRATE",
    Costrate: "COSTRATE",
} as const;
export type FindUserTeamManagersRequestSortColumn =
    (typeof FindUserTeamManagersRequestSortColumn)[keyof typeof FindUserTeamManagersRequestSortColumn];
