// This file was auto-generated by Fern from our API Definition.

export const ListTagsRequestSortOrder = {
    Ascending: "ASCENDING",
    Descending: "DESCENDING",
} as const;
export type ListTagsRequestSortOrder = (typeof ListTagsRequestSortOrder)[keyof typeof ListTagsRequestSortOrder];
