// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "64a687e29ae1f428e7ebe303",
 *         assignmentId: "5b641568b07987035750505e",
 *         repeat: true,
 *         weeks: 2
 *     }
 */
export interface ChangeRecurringPeriodRequest {
    /** Represents a workspace identifier across the system. */
    workspaceId: string;
    /** Represents an assignment identifier across the system. */
    assignmentId: string;
    /** Indicates whether assignment is recurring or not. */
    repeat: boolean;
    /** Indicates number of weeks for assignment. */
    weeks: number;
}
