// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../../../../index.js";

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         hoursPerDay: 1.1,
 *         period: {},
 *         projectId: "projectId",
 *         userId: "userId"
 *     }
 */
export interface CreateSchedulingRequest {
    workspaceId: string;
    billable?: boolean;
    excludeDays?: Record<string, unknown>[];
    hoursPerDay: number;
    includeNonWorkingDays?: boolean;
    note?: string;
    period: ClockifyApi.DateTimeInterval;
    projectId: string;
    /** Probes MUST keep published=false (draft) to avoid notifying other users. */
    published?: boolean;
    repeat?: boolean;
    taskId?: string;
    userId: string;
    weeks?: number;
}
