// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         end: "2024-01-15T09:30:00Z",
 *         start: "2024-01-15T09:30:00Z"
 *     }
 */
export interface PostWorkspacesWorkspaceIdSchedulingAssignmentsUsersTotalsRequest {
    workspaceId: string;
    end: string;
    start: string;
}
