// This file was auto-generated by Fern from our API Definition.

export const AddUserWorkspacesRequestSendEmail = {
    True: "true",
    False: "false",
} as const;
export type AddUserWorkspacesRequestSendEmail =
    (typeof AddUserWorkspacesRequestSendEmail)[keyof typeof AddUserWorkspacesRequestSendEmail];
