// This file was auto-generated by Fern from our API Definition.

export const GetTimeOffPoliciesRequestStatus = {
    Active: "ACTIVE",
    Archived: "ARCHIVED",
    All: "ALL",
} as const;
export type GetTimeOffPoliciesRequestStatus =
    (typeof GetTimeOffPoliciesRequestStatus)[keyof typeof GetTimeOffPoliciesRequestStatus];
