// This file was auto-generated by Fern from our API Definition.

export const ListTimeOffPoliciesRequestSortOrder = {
    Ascending: "ASCENDING",
    Descending: "DESCENDING",
} as const;
export type ListTimeOffPoliciesRequestSortOrder =
    (typeof ListTimeOffPoliciesRequestSortOrder)[keyof typeof ListTimeOffPoliciesRequestSortOrder];
