// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../../../../index.js";

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         automaticTimeEntryCreation: {
 *             defaultEntities: {
 *                 projectId: "65b36d3c525e243c48f9150f",
 *                 taskId: "65b36d46fa3df8607e42d21a"
 *             },
 *             enabled: false
 *         },
 *         color: "#8BC34A",
 *         datePeriod: {
 *             endDate: "2024-05-01",
 *             startDate: "2024-05-01"
 *         },
 *         everyoneIncludingNew: true,
 *         name: "Labour Day",
 *         occursAnnually: true,
 *         userGroups: {
 *             contains: "CONTAINS",
 *             ids: ["5b715612b079875110791342"],
 *             status: "ACTIVE"
 *         },
 *         users: {
 *             contains: "CONTAINS",
 *             ids: ["5b715612b079875110791432"],
 *             status: "ACTIVE"
 *         }
 *     }
 */
export interface CreateHolidayRequest {
    workspaceId: string;
    automaticTimeEntryCreation?: ClockifyApi.AutomaticTimeEntryCreationRequest;
    /** Color value in standard RGB hexadecimal format. */
    color?: string;
    datePeriod: ClockifyApi.DatePeriodRequest;
    /** Indicates whether the holiday is shown to new users. */
    everyoneIncludingNew?: boolean;
    /** Provide the name of the holiday. */
    name: string;
    /** Indicates whether the holiday occurs annually. */
    occursAnnually?: boolean;
    userGroups?: ClockifyApi.UserGroupIdsSchema;
    users?: ClockifyApi.UserIdsSchema;
}
