// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         "assigned-to": "60f924bafdaf031696ec6218"
 *     }
 */
export interface GetWorkspaceHolidaysRequest {
    workspaceId: string;
    /** If provided, returns a filtered list of holidays assigned to the user. */
    "assigned-to"?: string;
    /** 1-based page index. Default 1. */
    page?: number;
    /** Page size (number of items per page). Default 50; maximum 200. */
    "page-size"?: number;
}
