// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         tagId: "tagId"
 *     }
 */
export interface DeleteWorkspacesWorkspaceIdTagsTagIdRequest {
    workspaceId: string;
    tagId: string;
}
