// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         name: "name"
 *     }
 */
export interface TagCreate {
    workspaceId: string;
    name: string;
}
