// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../../../../index.js";

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         amountShown: "COST",
 *         amounts: ["EARNED", "COST"],
 *         approvalState: "APPROVED",
 *         archived: false,
 *         billable: true,
 *         clients: {
 *             contains: "CONTAINS",
 *             ids: ["5b715448b079875110792222"],
 *             status: "ACTIVE"
 *         },
 *         customFields: [{
 *                 id: "5b71544ab0798751107918b3",
 *                 isEmpty: false,
 *                 numberCondition: "EQUAL",
 *                 type: "NUMBER",
 *                 value: 2000
 *             }],
 *         dateFormat: "2018-11-01",
 *         dateRangeEnd: "2018-11-30T23:59:59.999",
 *         dateRangeStart: "2018-11-01T00:00:00",
 *         dateRangeType: "LAST_MONTH",
 *         description: "some description keyword",
 *         exportType: "JSON",
 *         invoicingState: "INVOICED",
 *         projects: {
 *             contains: "CONTAINS",
 *             ids: ["5b715448b079875110791111"],
 *             status: "ACTIVE"
 *         },
 *         rounding: false,
 *         sortOrder: "ASCENDING",
 *         timeFormat: "T00:00:00",
 *         timeZone: "Europe/Belgrade",
 *         userCustomFields: [{
 *                 id: "5b71544ab0798751107918b3",
 *                 isEmpty: false,
 *                 numberCondition: "EQUAL",
 *                 type: "NUMBER",
 *                 value: 2000
 *             }],
 *         userLocale: "en",
 *         weekStart: "MONDAY",
 *         weeklyFilter: {
 *             group: "USER",
 *             subgroup: "TIME"
 *         },
 *         withoutDescription: false,
 *         zoomLevel: "WEEK"
 *     }
 */
export interface WeeklyReportRequest {
    workspaceId: string;
    /** If provided, returns reports with the provided amount shown. */
    amountShown?: WeeklyReportRequest.AmountShown;
    /** Amount columns to include. */
    amounts?: ClockifyApi.AmountType[];
    /** If provided, returns reports with the provided approval state. */
    approvalState?: WeeklyReportRequest.ApprovalState;
    /** Indicates whether the report is archived. */
    archived?: boolean;
    /** Indicates whether the report is billable. */
    billable?: boolean;
    clients?: ClockifyApi.ContainsArchivedFilter;
    currency?: ClockifyApi.ContainsArchivedFilter;
    /** Time entry custom field filters. */
    customFields?: ClockifyApi.CustomFieldFilter[];
    /** Provide date in format YYYY-MM-DD. */
    dateFormat?: string;
    /** Provide date in format YYYY-MM-DDTHH:MM:SS.ssssss. Interpreted using the user's timezone or the provided timeZone. */
    dateRangeEnd: string;
    /** Provide date in format YYYY-MM-DDTHH:MM:SS.ssssss. Interpreted using the user's timezone or the provided timeZone. */
    dateRangeStart: string;
    /** Date range preset. */
    dateRangeType?: WeeklyReportRequest.DateRangeType;
    /** Search term for filtering report entries by description. */
    description?: string;
    /** Export format requested for the report. */
    exportType?: WeeklyReportRequest.ExportType;
    /** If provided, returns reports with the provided invoicing state. */
    invoicingState?: WeeklyReportRequest.InvoicingState;
    projects?: ClockifyApi.ContainsArchivedFilter;
    /** Indicates whether report filter rounding is enabled. */
    rounding?: boolean;
    /** Sort order. */
    sortOrder?: WeeklyReportRequest.SortOrder;
    tags?: ClockifyApi.ContainsTagFilter;
    tasks?: ClockifyApi.ContainsTaskFilter;
    /** Provide time in format THH:MM:SS.ssssss. */
    timeFormat?: string;
    /** Timezone used to interpret dates and times. */
    timeZone?: string;
    /** User custom field filters. */
    userCustomFields?: ClockifyApi.CustomFieldFilter[];
    userGroups?: ClockifyApi.ContainsUsersFilter;
    /** Locale used for report formatting. */
    userLocale?: string;
    users?: ClockifyApi.ContainsUsersFilter;
    /** Configured week start day. */
    weekStart?: WeeklyReportRequest.WeekStart;
    weeklyFilter: ClockifyApi.WeeklyFilter;
    /** If true, report includes only entries with empty description. */
    withoutDescription?: boolean;
    /** Report zoom level. */
    zoomLevel?: WeeklyReportRequest.ZoomLevel;
}

export namespace WeeklyReportRequest {
    /** If provided, returns reports with the provided amount shown. */
    export const AmountShown = {
        Earned: "EARNED",
        Cost: "COST",
        Profit: "PROFIT",
        HideAmount: "HIDE_AMOUNT",
        Export: "EXPORT",
    } as const;
    export type AmountShown = (typeof AmountShown)[keyof typeof AmountShown];
    /** If provided, returns reports with the provided approval state. */
    export const ApprovalState = {
        Approved: "APPROVED",
        Unapproved: "UNAPPROVED",
        All: "ALL",
    } as const;
    export type ApprovalState = (typeof ApprovalState)[keyof typeof ApprovalState];
    /** Date range preset. */
    export const DateRangeType = {
        Absolute: "ABSOLUTE",
        Today: "TODAY",
        Yesterday: "YESTERDAY",
        ThisWeek: "THIS_WEEK",
        LastWeek: "LAST_WEEK",
        PastTwoWeeks: "PAST_TWO_WEEKS",
        ThisMonth: "THIS_MONTH",
        LastMonth: "LAST_MONTH",
        ThisYear: "THIS_YEAR",
        LastYear: "LAST_YEAR",
    } as const;
    export type DateRangeType = (typeof DateRangeType)[keyof typeof DateRangeType];
    /** Export format requested for the report. */
    export const ExportType = {
        Json: "JSON",
        JsonV1: "JSON_V1",
        Pdf: "PDF",
        Csv: "CSV",
        Xlsx: "XLSX",
        Zip: "ZIP",
    } as const;
    export type ExportType = (typeof ExportType)[keyof typeof ExportType];
    /** If provided, returns reports with the provided invoicing state. */
    export const InvoicingState = {
        Invoiced: "INVOICED",
        Uninvoiced: "UNINVOICED",
        All: "ALL",
    } as const;
    export type InvoicingState = (typeof InvoicingState)[keyof typeof InvoicingState];
    /** Sort order. */
    export const SortOrder = {
        Ascending: "ASCENDING",
        Descending: "DESCENDING",
    } as const;
    export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder];
    /** Configured week start day. */
    export const WeekStart = {
        Monday: "MONDAY",
        Tuesday: "TUESDAY",
        Wednesday: "WEDNESDAY",
        Thursday: "THURSDAY",
        Friday: "FRIDAY",
        Saturday: "SATURDAY",
        Sunday: "SUNDAY",
    } as const;
    export type WeekStart = (typeof WeekStart)[keyof typeof WeekStart];
    /** Report zoom level. */
    export const ZoomLevel = {
        Week: "WEEK",
        Month: "MONTH",
        Year: "YEAR",
    } as const;
    export type ZoomLevel = (typeof ZoomLevel)[keyof typeof ZoomLevel];
}
