// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         invoiceId: "invoiceId",
 *         amount: 100,
 *         note: "This is a sample note for this invoice payment.",
 *         paymentDate: "2021-01-01T12:00:00Z"
 *     }
 */
export interface AddInvoicePaymentRequest {
    workspaceId: string;
    invoiceId: string;
    /** Represents an invoice payment amount as long. */
    amount: number;
    /** Represents an invoice payment note. */
    note?: string;
    /** Represents an invoice payment date in yyyy-MM-ddThh:mm:ssZ format. */
    paymentDate?: string;
}
