// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         invoiceId: "invoiceId",
 *         paymentId: "paymentId"
 *     }
 */
export interface DeleteInvoicePaymentRequest {
    workspaceId: string;
    invoiceId: string;
    paymentId: string;
}
