// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         invoiceId: "invoiceId"
 *     }
 */
export interface ListInvoicePaymentsRequest {
    workspaceId: string;
    invoiceId: string;
    /** 1-based page index. Default 1. */
    page?: number;
    /** Page size (number of items per page). Default 50; maximum 200. */
    "page-size"?: number;
}
