// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         sharedReportId: "sharedReportId"
 *     }
 */
export interface DeleteWorkspacesWorkspaceIdSharedReportsSharedReportIdRequest {
    workspaceId: string;
    sharedReportId: string;
}
