// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../../../../index.js";

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         policyId: "policyId"
 *     }
 */
export interface GetBalancesForPolicyRequest {
    workspaceId: string;
    policyId: string;
    /** Page number. */
    page?: number;
    /** Page size. */
    "page-size"?: number;
    /** If provided, the result is sorted by this column. */
    sort?: ClockifyApi.BalanceSortColumn;
    /** Sort results in ascending or descending order. */
    "sort-order"?: ClockifyApi.BalanceSortOrder;
}
