// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         userId: "userId"
 *     }
 */
export interface ListForUserBalancesRequest {
    workspaceId: string;
    userId: string;
}
