// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId"
 *     }
 */
export interface PatchWorkspacesWorkspaceIdBalanceRequest {
    workspaceId: string;
    amount?: number;
    note?: string;
    policyId?: string;
    userId?: string;
}
