// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "64a687e29ae1f428e7ebe303",
 *         customFieldId: "customFieldId"
 *     }
 */
export interface DeleteWorkspaceCustomFieldRequest {
    /** Represents a workspace identifier across the system. */
    workspaceId: string;
    customFieldId: string;
}
