// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         clientId: "clientId"
 *     }
 */
export interface GetWorkspacesWorkspaceIdClientsClientIdRequest {
    workspaceId: string;
    clientId: string;
}
