// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         expenseId: "expenseId"
 *     }
 */
export interface DeleteExpensesRequest {
    workspaceId: string;
    expenseId: string;
}
