// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../core/index.js";

/**
 * @example
 *     {
 *         file: fs.createReadStream("/path/to/your/file"),
 *         workspaceId: "workspaceId",
 *         amount: 1.1,
 *         categoryId: "categoryId",
 *         date: "2024-01-15T09:30:00Z",
 *         projectId: "projectId",
 *         userId: "userId"
 *     }
 */
export interface ExpenseCreateRequest {
    workspaceId: string;
    /**
     * Represents an expense amount as the double data type.
     * Live expense responses expose this value as quantity.
     */
    amount: number;
    /** Indicates whether expense is billable or not. */
    billable?: boolean;
    /** Represents a category identifier across the system. */
    categoryId: string;
    /** Provides a valid yyyy-MM-ddThh:mm:ssZ format date. */
    date: string;
    file: core.file.Uploadable;
    /** Represents notes for an expense. */
    notes?: string;
    /** Represents a project identifier across the system. */
    projectId: string;
    /** Represents a task identifier across the system. */
    taskId?: string;
    /** Represents a user identifier across the system. */
    userId: string;
}
