// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId"
 *     }
 */
export interface GetWorkspacesWorkspaceIdPoliciesRequest {
    workspaceId: string;
    archived?: boolean;
}
