// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         policyId: "policyId"
 *     }
 */
export interface GetWorkspacesWorkspaceIdPoliciesPolicyIdRequest {
    workspaceId: string;
    policyId: string;
}
