// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../../../../index.js";

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         body: {}
 *     }
 */
export interface PostWorkspacesWorkspaceIdPoliciesRequest {
    workspaceId: string;
    body: ClockifyApi.TimeOffPolicy;
}
