// This file was auto-generated by Fern from our API Definition.

export const GetSharedReportsSharedReportIdRequestExportType = {
    JsonV1: "JSON_V1",
    Json: "JSON",
    Csv: "CSV",
    Xlsx: "XLSX",
    Pdf: "PDF",
} as const;
export type GetSharedReportsSharedReportIdRequestExportType =
    (typeof GetSharedReportsSharedReportIdRequestExportType)[keyof typeof GetSharedReportsSharedReportIdRequestExportType];
