// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         groupId: "groupId",
 *         userId: "5a0ab5acb07987125438b60f"
 *     }
 */
export interface AddUserToGroupRequest {
    workspaceId: string;
    groupId: string;
    /** Represents a user identifier across the system. */
    userId: string;
}
