// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         groupId: "groupId"
 *     }
 */
export interface GetWorkspacesWorkspaceIdUserGroupsGroupIdUsersRequest {
    workspaceId: string;
    groupId: string;
}
