// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../../../../index.js";

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         groupId: "groupId",
 *         body: {
 *             name: "development_team"
 *         }
 *     }
 */
export interface UpdateUserGroupsRequest {
    workspaceId: string;
    groupId: string;
    body: ClockifyApi.UserGroupRequest;
}
