import { defineConfig } from "vitest/config";

export default defineConfig({
    test: {
        environment: "node",
        globals: false,
        include: ["tests/**/*.test.ts"],
        testTimeout: 30_000,
        hookTimeout: 30_000,
        // Type tests live in tests/types/*.test-d.ts and run on demand
        // via `npm run test:types` (`vitest --typecheck.only`). Default
        // `npm test` skips them — `enabled: false` matches vitest's
        // default and is repeated here for clarity.
        typecheck: {
            enabled: false,
            tsconfig: "./tsconfig.json",
            include: ["tests/types/**/*.test-d.ts"],
        },
        coverage: {
            // Hand-written wrapper surface only. The generated client under
            // src/** is regenerated by ../GOCLMCP/ and is a hard-stop no-edit
            // zone, so it is excluded. webhook-events.ts is a flat generated
            // type catalog (no runnable logic). Thresholds are pinned to the
            // honest measured baseline in docs/coverage-contract.json.
            provider: "v8",
            reporter: ["text-summary", "json-summary"],
            reportsDirectory: "./coverage",
            include: ["*.ts"],
            exclude: [
                "src/**",
                "scripts/**",
                "tests/**",
                "dist/**",
                "*.config.*",
                "webhook-events.ts",
            ],
            // Mirror docs/coverage-contract.json so bare `vitest run --coverage`
            // enforces locally too. The cross-package monotonic ratchet remains
            // scripts/check-coverage-floor.mjs (`make coverage`); keep both in
            // lockstep when floors change.
            thresholds: {
                lines: 90,
                functions: 81,
                branches: 81,
                statements: 89,
            },
        },
    },
});
