// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         policyId: "policyId",
 *         requestId: "requestId"
 *     }
 */
export interface DeleteTimeOffRequestRequest {
    workspaceId: string;
    policyId: string;
    requestId: string;
}
