// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         policyId: "policyId",
 *         requestId: "requestId",
 *         statusType: "APPROVED"
 *     }
 */
export interface PatchWorkspacesWorkspaceIdPoliciesPolicyIdRequestsRequestIdRequest {
    workspaceId: string;
    policyId: string;
    requestId: string;
    note?: string;
    statusType: PatchWorkspacesWorkspaceIdPoliciesPolicyIdRequestsRequestIdRequest.StatusType;
}

export namespace PatchWorkspacesWorkspaceIdPoliciesPolicyIdRequestsRequestIdRequest {
    export const StatusType = {
        Approved: "APPROVED",
        Rejected: "REJECTED",
    } as const;
    export type StatusType = (typeof StatusType)[keyof typeof StatusType];
}
