// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         policyId: "policyId",
 *         timeOffPeriod: {
 *             period: {
 *                 end: "2026-07-13T10:00:00Z",
 *                 start: "2026-07-13T09:00:00Z"
 *             }
 *         }
 *     }
 */
export interface PostWorkspacesWorkspaceIdPoliciesPolicyIdRequestsRequest {
    workspaceId: string;
    policyId: string;
    note?: string;
    timeOffPeriod: PostWorkspacesWorkspaceIdPoliciesPolicyIdRequestsRequest.TimeOffPeriod;
}

export namespace PostWorkspacesWorkspaceIdPoliciesPolicyIdRequestsRequest {
    export interface TimeOffPeriod {
        halfDayPeriod?: TimeOffPeriod.HalfDayPeriod | undefined;
        isHalfDay?: boolean | undefined;
        period: TimeOffPeriod.Period;
        /** Optional; defaults to user's timeZone */
        timeZone?: string | undefined;
    }

    export namespace TimeOffPeriod {
        export const HalfDayPeriod = {
            FirstHalf: "FIRST_HALF",
            SecondHalf: "SECOND_HALF",
            NotDefined: "NOT_DEFINED",
        } as const;
        export type HalfDayPeriod = (typeof HalfDayPeriod)[keyof typeof HalfDayPeriod];

        export interface Period {
            end: string;
            start: string;
        }
    }
}
