// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         requestId: "requestId"
 *     }
 */
export interface UpdateStatusTimeOffRequest {
    workspaceId: string;
    requestId: string;
    note?: string;
    statusType?: UpdateStatusTimeOffRequest.StatusType;
}

export namespace UpdateStatusTimeOffRequest {
    export const StatusType = {
        Approved: "APPROVED",
        Rejected: "REJECTED",
        Withdrawn: "WITHDRAWN",
    } as const;
    export type StatusType = (typeof StatusType)[keyof typeof StatusType];
}
