// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../../../../index.js";

/**
 * @example
 *     {
 *         workspaceId: "64a687e29ae1f428e7ebe303",
 *         userId: "5a0ab5acb07987125438b60f"
 *     }
 */
export interface FindUserTeamManagersRequest {
    /** Represents a workspace identifier across the system. */
    workspaceId: string;
    /** Represents a user identifier across the system. */
    userId: string;
    /** Sorting column criteria. */
    "sort-column"?: ClockifyApi.FindUserTeamManagersRequestSortColumn;
    /** Sorting mode. */
    "sort-order"?: ClockifyApi.FindUserTeamManagersRequestSortOrder;
    /** Page number. */
    page?: number;
    /** Page size. */
    "page-size"?: number;
}
