// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "64a687e29ae1f428e7ebe303",
 *         userId: "5a0ab5acb07987125438b60f",
 *         customFieldId: "5e4117fe8c625f38930d57b7",
 *         value: "20231211-12345"
 *     }
 */
export interface UpdateUserCustomFieldValueRequest {
    /** Represents a workspace identifier across the system. */
    workspaceId: string;
    /** Represents a user identifier across the system. */
    userId: string;
    /** Represents a custom field identifier across the system. */
    customFieldId: string;
    /** Represents custom field value. */
    value: unknown | null;
}
