// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import type * as ClockifyApi from "../../../index.js";

export declare namespace TimeEntriesClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class TimeEntriesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<TimeEntriesClient.Options>;

    constructor(options: TimeEntriesClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {ClockifyApi.CreateTimeEntryRequest} request
     * @param {TimeEntriesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.timeEntries.postWorkspacesWorkspaceIdTimeEntries({
     *         workspaceId: "workspaceId",
     *         start: "2024-01-15T09:30:00Z"
     *     })
     */
    public postWorkspacesWorkspaceIdTimeEntries(
        request: ClockifyApi.CreateTimeEntryRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): core.HttpResponsePromise<ClockifyApi.TimeEntriesTimeEntry> {
        return core.HttpResponsePromise.fromPromise(
            this.__postWorkspacesWorkspaceIdTimeEntries(request, requestOptions),
        );
    }

    private async __postWorkspacesWorkspaceIdTimeEntries(
        request: ClockifyApi.CreateTimeEntryRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): Promise<core.WithRawResponse<ClockifyApi.TimeEntriesTimeEntry>> {
        const { workspaceId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Addon-Token": requestOptions?.addonToken ?? this._options?.addonToken }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ClockifyApiEnvironment.Default,
                `workspaces/${core.url.encodePathParam(workspaceId)}/time-entries`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ClockifyApi.TimeEntriesTimeEntry, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ClockifyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/workspaces/{workspaceId}/time-entries",
        );
    }

    /**
     * @param {ClockifyApi.PatchWorkspacesWorkspaceIdTimeEntriesInvoicedRequest} request
     * @param {TimeEntriesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.timeEntries.patchWorkspacesWorkspaceIdTimeEntriesInvoiced({
     *         workspaceId: "workspaceId",
     *         invoiced: true,
     *         timeEntryIds: ["timeEntryIds"]
     *     })
     */
    public patchWorkspacesWorkspaceIdTimeEntriesInvoiced(
        request: ClockifyApi.PatchWorkspacesWorkspaceIdTimeEntriesInvoicedRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(
            this.__patchWorkspacesWorkspaceIdTimeEntriesInvoiced(request, requestOptions),
        );
    }

    private async __patchWorkspacesWorkspaceIdTimeEntriesInvoiced(
        request: ClockifyApi.PatchWorkspacesWorkspaceIdTimeEntriesInvoicedRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { workspaceId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Addon-Token": requestOptions?.addonToken ?? this._options?.addonToken }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ClockifyApiEnvironment.Default,
                `workspaces/${core.url.encodePathParam(workspaceId)}/time-entries/invoiced`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ClockifyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/workspaces/{workspaceId}/time-entries/invoiced",
        );
    }

    /**
     * @param {ClockifyApi.PatchWorkspacesWorkspaceIdTimeEntriesInvoicedBulkRequest} request
     * @param {TimeEntriesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.timeEntries.patchWorkspacesWorkspaceIdTimeEntriesInvoicedBulk({
     *         workspaceId: "workspaceId"
     *     })
     */
    public patchWorkspacesWorkspaceIdTimeEntriesInvoicedBulk(
        request: ClockifyApi.PatchWorkspacesWorkspaceIdTimeEntriesInvoicedBulkRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(
            this.__patchWorkspacesWorkspaceIdTimeEntriesInvoicedBulk(request, requestOptions),
        );
    }

    private async __patchWorkspacesWorkspaceIdTimeEntriesInvoicedBulk(
        request: ClockifyApi.PatchWorkspacesWorkspaceIdTimeEntriesInvoicedBulkRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { workspaceId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Addon-Token": requestOptions?.addonToken ?? this._options?.addonToken }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ClockifyApiEnvironment.Default,
                `workspaces/${core.url.encodePathParam(workspaceId)}/time-entries/invoiced/bulk`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ClockifyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/workspaces/{workspaceId}/time-entries/invoiced/bulk",
        );
    }

    /**
     * @param {ClockifyApi.GetWorkspacesWorkspaceIdTimeEntriesStatusInProgressRequest} request
     * @param {TimeEntriesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.timeEntries.getWorkspacesWorkspaceIdTimeEntriesStatusInProgress({
     *         workspaceId: "workspaceId"
     *     })
     */
    public getWorkspacesWorkspaceIdTimeEntriesStatusInProgress(
        request: ClockifyApi.GetWorkspacesWorkspaceIdTimeEntriesStatusInProgressRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): core.HttpResponsePromise<ClockifyApi.TimeEntriesTimeEntry[]> {
        return core.HttpResponsePromise.fromPromise(
            this.__getWorkspacesWorkspaceIdTimeEntriesStatusInProgress(request, requestOptions),
        );
    }

    private async __getWorkspacesWorkspaceIdTimeEntriesStatusInProgress(
        request: ClockifyApi.GetWorkspacesWorkspaceIdTimeEntriesStatusInProgressRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): Promise<core.WithRawResponse<ClockifyApi.TimeEntriesTimeEntry[]>> {
        const { workspaceId, page, "page-size": pageSize } = request;
        const _queryParams: Record<string, unknown> = {
            page,
            "page-size": pageSize,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Addon-Token": requestOptions?.addonToken ?? this._options?.addonToken }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ClockifyApiEnvironment.Default,
                `workspaces/${core.url.encodePathParam(workspaceId)}/time-entries/status/in-progress`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ClockifyApi.TimeEntriesTimeEntry[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ClockifyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/workspaces/{workspaceId}/time-entries/status/in-progress",
        );
    }

    /**
     * @param {ClockifyApi.GetWorkspacesWorkspaceIdTimeEntriesTimeEntryIdRequest} request
     * @param {TimeEntriesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.timeEntries.getWorkspacesWorkspaceIdTimeEntriesTimeEntryId({
     *         workspaceId: "workspaceId",
     *         timeEntryId: "timeEntryId"
     *     })
     */
    public getWorkspacesWorkspaceIdTimeEntriesTimeEntryId(
        request: ClockifyApi.GetWorkspacesWorkspaceIdTimeEntriesTimeEntryIdRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): core.HttpResponsePromise<ClockifyApi.TimeEntry> {
        return core.HttpResponsePromise.fromPromise(
            this.__getWorkspacesWorkspaceIdTimeEntriesTimeEntryId(request, requestOptions),
        );
    }

    private async __getWorkspacesWorkspaceIdTimeEntriesTimeEntryId(
        request: ClockifyApi.GetWorkspacesWorkspaceIdTimeEntriesTimeEntryIdRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): Promise<core.WithRawResponse<ClockifyApi.TimeEntry>> {
        const { workspaceId, timeEntryId, hydrated, "consider-duration-format": considerDurationFormat } = request;
        const _queryParams: Record<string, unknown> = {
            hydrated,
            "consider-duration-format": considerDurationFormat,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Addon-Token": requestOptions?.addonToken ?? this._options?.addonToken }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ClockifyApiEnvironment.Default,
                `workspaces/${core.url.encodePathParam(workspaceId)}/time-entries/${core.url.encodePathParam(timeEntryId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ClockifyApi.TimeEntry, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ClockifyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/workspaces/{workspaceId}/time-entries/{timeEntryId}",
        );
    }

    /**
     * @param {ClockifyApi.PutWorkspacesWorkspaceIdTimeEntriesTimeEntryIdRequest} request
     * @param {TimeEntriesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.timeEntries.putWorkspacesWorkspaceIdTimeEntriesTimeEntryId({
     *         workspaceId: "workspaceId",
     *         timeEntryId: "timeEntryId",
     *         body: {
     *             start: "2024-01-15T09:30:00Z"
     *         }
     *     })
     */
    public putWorkspacesWorkspaceIdTimeEntriesTimeEntryId(
        request: ClockifyApi.PutWorkspacesWorkspaceIdTimeEntriesTimeEntryIdRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): core.HttpResponsePromise<ClockifyApi.TimeEntry> {
        return core.HttpResponsePromise.fromPromise(
            this.__putWorkspacesWorkspaceIdTimeEntriesTimeEntryId(request, requestOptions),
        );
    }

    private async __putWorkspacesWorkspaceIdTimeEntriesTimeEntryId(
        request: ClockifyApi.PutWorkspacesWorkspaceIdTimeEntriesTimeEntryIdRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): Promise<core.WithRawResponse<ClockifyApi.TimeEntry>> {
        const { workspaceId, timeEntryId, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Addon-Token": requestOptions?.addonToken ?? this._options?.addonToken }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ClockifyApiEnvironment.Default,
                `workspaces/${core.url.encodePathParam(workspaceId)}/time-entries/${core.url.encodePathParam(timeEntryId)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ClockifyApi.TimeEntry, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ClockifyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/workspaces/{workspaceId}/time-entries/{timeEntryId}",
        );
    }

    /**
     * @param {ClockifyApi.DeleteWorkspacesWorkspaceIdTimeEntriesTimeEntryIdRequest} request
     * @param {TimeEntriesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.timeEntries.deleteWorkspacesWorkspaceIdTimeEntriesTimeEntryId({
     *         workspaceId: "workspaceId",
     *         timeEntryId: "timeEntryId"
     *     })
     */
    public deleteWorkspacesWorkspaceIdTimeEntriesTimeEntryId(
        request: ClockifyApi.DeleteWorkspacesWorkspaceIdTimeEntriesTimeEntryIdRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(
            this.__deleteWorkspacesWorkspaceIdTimeEntriesTimeEntryId(request, requestOptions),
        );
    }

    private async __deleteWorkspacesWorkspaceIdTimeEntriesTimeEntryId(
        request: ClockifyApi.DeleteWorkspacesWorkspaceIdTimeEntriesTimeEntryIdRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { workspaceId, timeEntryId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Addon-Token": requestOptions?.addonToken ?? this._options?.addonToken }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ClockifyApiEnvironment.Default,
                `workspaces/${core.url.encodePathParam(workspaceId)}/time-entries/${core.url.encodePathParam(timeEntryId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ClockifyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/workspaces/{workspaceId}/time-entries/{timeEntryId}",
        );
    }

    /**
     * @param {ClockifyApi.GetWorkspacesWorkspaceIdUserUserIdTimeEntriesRequest} request
     * @param {TimeEntriesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.timeEntries.getWorkspacesWorkspaceIdUserUserIdTimeEntries({
     *         workspaceId: "workspaceId",
     *         userId: "userId"
     *     })
     */
    public getWorkspacesWorkspaceIdUserUserIdTimeEntries(
        request: ClockifyApi.GetWorkspacesWorkspaceIdUserUserIdTimeEntriesRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): core.HttpResponsePromise<ClockifyApi.TimeEntry[]> {
        return core.HttpResponsePromise.fromPromise(
            this.__getWorkspacesWorkspaceIdUserUserIdTimeEntries(request, requestOptions),
        );
    }

    private async __getWorkspacesWorkspaceIdUserUserIdTimeEntries(
        request: ClockifyApi.GetWorkspacesWorkspaceIdUserUserIdTimeEntriesRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): Promise<core.WithRawResponse<ClockifyApi.TimeEntry[]>> {
        const {
            workspaceId,
            userId,
            description,
            start,
            end,
            project,
            task,
            tags,
            "project-required": projectRequired,
            "task-required": taskRequired,
            hydrated,
            "in-progress": inProgress,
            "get-week-before": getWeekBefore,
            page,
            "page-size": pageSize,
        } = request;
        const _queryParams: Record<string, unknown> = {
            description,
            start: start != null ? start : undefined,
            end: end != null ? end : undefined,
            project,
            task,
            tags,
            "project-required": projectRequired,
            "task-required": taskRequired,
            hydrated,
            "in-progress": inProgress,
            "get-week-before": getWeekBefore != null ? getWeekBefore : undefined,
            page,
            "page-size": pageSize,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Addon-Token": requestOptions?.addonToken ?? this._options?.addonToken }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ClockifyApiEnvironment.Default,
                `workspaces/${core.url.encodePathParam(workspaceId)}/user/${core.url.encodePathParam(userId)}/time-entries`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ClockifyApi.TimeEntry[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ClockifyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/workspaces/{workspaceId}/user/{userId}/time-entries",
        );
    }

    /**
     * @param {ClockifyApi.PostWorkspacesWorkspaceIdUserUserIdTimeEntriesRequest} request
     * @param {TimeEntriesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.timeEntries.postWorkspacesWorkspaceIdUserUserIdTimeEntries({
     *         workspaceId: "workspaceId",
     *         userId: "userId",
     *         body: {
     *             start: "2024-01-15T09:30:00Z"
     *         }
     *     })
     */
    public postWorkspacesWorkspaceIdUserUserIdTimeEntries(
        request: ClockifyApi.PostWorkspacesWorkspaceIdUserUserIdTimeEntriesRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): core.HttpResponsePromise<ClockifyApi.TimeEntry> {
        return core.HttpResponsePromise.fromPromise(
            this.__postWorkspacesWorkspaceIdUserUserIdTimeEntries(request, requestOptions),
        );
    }

    private async __postWorkspacesWorkspaceIdUserUserIdTimeEntries(
        request: ClockifyApi.PostWorkspacesWorkspaceIdUserUserIdTimeEntriesRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): Promise<core.WithRawResponse<ClockifyApi.TimeEntry>> {
        const { workspaceId, userId, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Addon-Token": requestOptions?.addonToken ?? this._options?.addonToken }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ClockifyApiEnvironment.Default,
                `workspaces/${core.url.encodePathParam(workspaceId)}/user/${core.url.encodePathParam(userId)}/time-entries`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ClockifyApi.TimeEntry, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ClockifyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/workspaces/{workspaceId}/user/{userId}/time-entries",
        );
    }

    /**
     * @param {ClockifyApi.PutWorkspacesWorkspaceIdUserUserIdTimeEntriesRequest} request
     * @param {TimeEntriesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.timeEntries.putWorkspacesWorkspaceIdUserUserIdTimeEntries({
     *         workspaceId: "workspaceId",
     *         userId: "userId",
     *         body: [{
     *                 end: "2024-01-15T09:30:00Z",
     *                 id: "id",
     *                 start: "2024-01-15T09:30:00Z"
     *             }]
     *     })
     */
    public putWorkspacesWorkspaceIdUserUserIdTimeEntries(
        request: ClockifyApi.PutWorkspacesWorkspaceIdUserUserIdTimeEntriesRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): core.HttpResponsePromise<ClockifyApi.TimeEntriesTimeEntry[]> {
        return core.HttpResponsePromise.fromPromise(
            this.__putWorkspacesWorkspaceIdUserUserIdTimeEntries(request, requestOptions),
        );
    }

    private async __putWorkspacesWorkspaceIdUserUserIdTimeEntries(
        request: ClockifyApi.PutWorkspacesWorkspaceIdUserUserIdTimeEntriesRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): Promise<core.WithRawResponse<ClockifyApi.TimeEntriesTimeEntry[]>> {
        const { workspaceId, userId, body: _body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Addon-Token": requestOptions?.addonToken ?? this._options?.addonToken }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ClockifyApiEnvironment.Default,
                `workspaces/${core.url.encodePathParam(workspaceId)}/user/${core.url.encodePathParam(userId)}/time-entries`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ClockifyApi.TimeEntriesTimeEntry[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ClockifyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/workspaces/{workspaceId}/user/{userId}/time-entries",
        );
    }

    /**
     * @param {ClockifyApi.DeleteManyRequest} request
     * @param {TimeEntriesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.timeEntries.deleteMany({
     *         workspaceId: "64a687e29ae1f428e7ebe303",
     *         userId: "5a0ab5acb07987125438b60f",
     *         "time-entry-ids": ["5a0ab5acb07987125438b60f"]
     *     })
     */
    public deleteMany(
        request: ClockifyApi.DeleteManyRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): core.HttpResponsePromise<ClockifyApi.TimeEntryDtoImplV1[]> {
        return core.HttpResponsePromise.fromPromise(this.__deleteMany(request, requestOptions));
    }

    private async __deleteMany(
        request: ClockifyApi.DeleteManyRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): Promise<core.WithRawResponse<ClockifyApi.TimeEntryDtoImplV1[]>> {
        const { workspaceId, userId, "time-entry-ids": timeEntryIds } = request;
        const _queryParams: Record<string, unknown> = {
            "time-entry-ids": timeEntryIds,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Addon-Token": requestOptions?.addonToken ?? this._options?.addonToken }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ClockifyApiEnvironment.Default,
                `workspaces/${core.url.encodePathParam(workspaceId)}/user/${core.url.encodePathParam(userId)}/time-entries`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ClockifyApi.TimeEntryDtoImplV1[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ClockifyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/workspaces/{workspaceId}/user/{userId}/time-entries",
        );
    }

    /**
     * @param {ClockifyApi.PatchWorkspacesWorkspaceIdUserUserIdTimeEntriesRequest} request
     * @param {TimeEntriesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.timeEntries.patchWorkspacesWorkspaceIdUserUserIdTimeEntries({
     *         workspaceId: "workspaceId",
     *         userId: "userId",
     *         end: "2024-01-15T09:30:00Z"
     *     })
     */
    public patchWorkspacesWorkspaceIdUserUserIdTimeEntries(
        request: ClockifyApi.PatchWorkspacesWorkspaceIdUserUserIdTimeEntriesRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): core.HttpResponsePromise<ClockifyApi.TimeEntriesTimeEntry> {
        return core.HttpResponsePromise.fromPromise(
            this.__patchWorkspacesWorkspaceIdUserUserIdTimeEntries(request, requestOptions),
        );
    }

    private async __patchWorkspacesWorkspaceIdUserUserIdTimeEntries(
        request: ClockifyApi.PatchWorkspacesWorkspaceIdUserUserIdTimeEntriesRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): Promise<core.WithRawResponse<ClockifyApi.TimeEntriesTimeEntry>> {
        const { workspaceId, userId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Addon-Token": requestOptions?.addonToken ?? this._options?.addonToken }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ClockifyApiEnvironment.Default,
                `workspaces/${core.url.encodePathParam(workspaceId)}/user/${core.url.encodePathParam(userId)}/time-entries`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ClockifyApi.TimeEntriesTimeEntry, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ClockifyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/workspaces/{workspaceId}/user/{userId}/time-entries",
        );
    }

    /**
     * @param {ClockifyApi.PatchWorkspacesWorkspaceIdUserUserIdTimeEntriesStopRequest} request
     * @param {TimeEntriesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.timeEntries.patchWorkspacesWorkspaceIdUserUserIdTimeEntriesStop({
     *         workspaceId: "workspaceId",
     *         userId: "userId",
     *         end: "2024-01-15T09:30:00Z"
     *     })
     */
    public patchWorkspacesWorkspaceIdUserUserIdTimeEntriesStop(
        request: ClockifyApi.PatchWorkspacesWorkspaceIdUserUserIdTimeEntriesStopRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): core.HttpResponsePromise<ClockifyApi.TimeEntry> {
        return core.HttpResponsePromise.fromPromise(
            this.__patchWorkspacesWorkspaceIdUserUserIdTimeEntriesStop(request, requestOptions),
        );
    }

    private async __patchWorkspacesWorkspaceIdUserUserIdTimeEntriesStop(
        request: ClockifyApi.PatchWorkspacesWorkspaceIdUserUserIdTimeEntriesStopRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): Promise<core.WithRawResponse<ClockifyApi.TimeEntry>> {
        const { workspaceId, userId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Addon-Token": requestOptions?.addonToken ?? this._options?.addonToken }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ClockifyApiEnvironment.Default,
                `workspaces/${core.url.encodePathParam(workspaceId)}/user/${core.url.encodePathParam(userId)}/time-entries/stop`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ClockifyApi.TimeEntry, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ClockifyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/workspaces/{workspaceId}/user/{userId}/time-entries/stop",
        );
    }

    /**
     * @param {ClockifyApi.PostWorkspacesWorkspaceIdUserUserIdTimeEntriesTimeEntryIdDuplicateRequest} request
     * @param {TimeEntriesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.timeEntries.postWorkspacesWorkspaceIdUserUserIdTimeEntriesTimeEntryIdDuplicate({
     *         workspaceId: "workspaceId",
     *         userId: "userId",
     *         timeEntryId: "timeEntryId"
     *     })
     */
    public postWorkspacesWorkspaceIdUserUserIdTimeEntriesTimeEntryIdDuplicate(
        request: ClockifyApi.PostWorkspacesWorkspaceIdUserUserIdTimeEntriesTimeEntryIdDuplicateRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): core.HttpResponsePromise<ClockifyApi.TimeEntriesTimeEntry> {
        return core.HttpResponsePromise.fromPromise(
            this.__postWorkspacesWorkspaceIdUserUserIdTimeEntriesTimeEntryIdDuplicate(request, requestOptions),
        );
    }

    private async __postWorkspacesWorkspaceIdUserUserIdTimeEntriesTimeEntryIdDuplicate(
        request: ClockifyApi.PostWorkspacesWorkspaceIdUserUserIdTimeEntriesTimeEntryIdDuplicateRequest,
        requestOptions?: TimeEntriesClient.RequestOptions,
    ): Promise<core.WithRawResponse<ClockifyApi.TimeEntriesTimeEntry>> {
        const { workspaceId, userId, timeEntryId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Addon-Token": requestOptions?.addonToken ?? this._options?.addonToken }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ClockifyApiEnvironment.Default,
                `workspaces/${core.url.encodePathParam(workspaceId)}/user/${core.url.encodePathParam(userId)}/time-entries/${core.url.encodePathParam(timeEntryId)}/duplicate`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as ClockifyApi.TimeEntriesTimeEntry, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ClockifyApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/workspaces/{workspaceId}/user/{userId}/time-entries/{timeEntryId}/duplicate",
        );
    }
}
