// This file was auto-generated by Fern from our API Definition.

export const ListClientsRequestSortOrder = {
    Ascending: "ASCENDING",
    Descending: "DESCENDING",
} as const;
export type ListClientsRequestSortOrder =
    (typeof ListClientsRequestSortOrder)[keyof typeof ListClientsRequestSortOrder];
