/**
 * Generate per-resource markdown reference from the synced SDK.
 *
 * For each resource under wrapper/src/api/resources/, parses the
 * generated Client.ts for method signatures and the matching
 * client/requests/*.ts files for request-field declarations, then
 * emits wrapper/docs/resources/<resource>.md with a method list +
 * per-method JSDoc snippet + compact field summary.
 *
 * Output is committed (gives PR diffs a signal when the SDK shape
 * shifts between regens). Run via:
 *
 *   npx tsx scripts/gen-resource-docs.ts
 *
 * Chained into `npm run sync` so a stale sync surfaces as docs
 * changes in the same PR.
 */
import {
    existsSync,
    mkdirSync,
    readFileSync,
    readdirSync,
    statSync,
    writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const WRAPPER_ROOT = resolve(__dirname, "..");
const RESOURCES_DIR = join(WRAPPER_ROOT, "src/api/resources");
const OUT_DIR = join(WRAPPER_ROOT, "docs/resources");

interface MethodEntry {
    name: string;
    requestType: string | undefined;
    jsDoc: string;
}

interface FieldEntry {
    name: string;
    type: string;
    required: boolean;
    description: string | undefined;
}

if (!existsSync(RESOURCES_DIR)) {
    console.error(
        `error: ${RESOURCES_DIR} not found. Did you forget to run 'npm run sync'?`,
    );
    process.exit(1);
}

mkdirSync(OUT_DIR, { recursive: true });

const resources = readdirSync(RESOURCES_DIR).filter((d) =>
    statSync(join(RESOURCES_DIR, d)).isDirectory(),
);

let totalMethods = 0;
const indexLines: string[] = ["# Resource reference\n"];
indexLines.push(
    `One markdown file per Clockify API resource (${resources.length} resources total). ` +
        "Auto-generated by `wrapper/scripts/gen-resource-docs.ts` from the synced " +
        "SDK; do not edit by hand. For full type expansions and link-walking, " +
        "see the [TypeDoc reference](../api/) (built into `docs/api/` by " +
        "`npm run docs`).\n",
);
indexLines.push("| Resource | Methods | File |", "|---|---|---|");

for (const resource of resources) {
    const clientFile = join(RESOURCES_DIR, resource, "client/Client.ts");
    if (!existsSync(clientFile)) continue;

    const methods = parseMethods(readFileSync(clientFile, "utf8"));
    totalMethods += methods.length;

    const md: string[] = [];
    md.push(`# ${resource}`);
    md.push("");
    md.push(`${methods.length} methods on \`client.${resource}\`.`);
    md.push("");
    md.push(
        `> Compact reference auto-generated from the synced SDK. ` +
            `For full type expansions, see the [TypeDoc reference](../api/).`,
    );
    md.push("");
    md.push("## Methods");
    md.push("");

    for (const m of methods) {
        md.push(`### \`${m.name}\``);
        md.push("");
        const example = extractExample(m.jsDoc);
        if (example) md.push("**Example:**", "", "```typescript", example, "```", "");

        if (m.requestType != null) {
            const reqFile = join(
                RESOURCES_DIR,
                resource,
                "client/requests",
                `${m.requestType}.ts`,
            );
            if (existsSync(reqFile)) {
                const fields = parseFields(readFileSync(reqFile, "utf8"));
                if (fields.length > 0) {
                    md.push(`**Request fields** (\`${m.requestType}\`):`, "");
                    for (const f of fields) {
                        const req = f.required ? "required" : "optional";
                        const desc = f.description ? ` — ${f.description}` : "";
                        md.push(`- \`${f.name}\` (\`${f.type}\`, ${req})${desc}`);
                    }
                    md.push("");
                }
            }
        }
    }

    writeFileSync(join(OUT_DIR, `${resource}.md`), md.join("\n") + "\n");
    indexLines.push(
        `| ${resource} | ${methods.length} | [\`${resource}.md\`](./${resource}.md) |`,
    );
}

writeFileSync(join(OUT_DIR, "README.md"), indexLines.join("\n") + "\n");

console.log(
    `Generated docs for ${resources.length} resources (${totalMethods} methods total) into ${OUT_DIR}`,
);

// ---------- parsers ----------

function parseMethods(text: string): MethodEntry[] {
    const out: MethodEntry[] = [];
    const lines = text.split("\n");
    let pendingJsDoc: string[] = [];
    let inJsDoc = false;

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i]!;

        if (line.trim().startsWith("/**")) {
            inJsDoc = true;
            pendingJsDoc = [line];
            if (line.includes("*/")) inJsDoc = false;
            continue;
        }
        if (inJsDoc) {
            pendingJsDoc.push(line);
            if (line.includes("*/")) inJsDoc = false;
            continue;
        }

        const m = line.match(/^\s{4}public (?:async )?([a-zA-Z]+)\(/);
        if (m && !m[1]!.startsWith("__")) {
            const name = m[1]!;
            let requestType: string | undefined;
            for (let j = i + 1; j < Math.min(i + 5, lines.length); j++) {
                const reqMatch = lines[j]!.match(/request: ClockifyApi\.([A-Z][a-zA-Z]+)/);
                if (reqMatch) {
                    requestType = reqMatch[1]!;
                    break;
                }
            }
            out.push({ name, requestType, jsDoc: pendingJsDoc.join("\n") });
            pendingJsDoc = [];
        } else if (line.trim().length > 0 && pendingJsDoc.length > 0) {
            // JSDoc was for something other than a method; discard
            pendingJsDoc = [];
        }
    }
    return out;
}

function parseFields(text: string): FieldEntry[] {
    const out: FieldEntry[] = [];
    const lines = text.split("\n");
    let pendingComment: string | undefined;
    let inInterface = false;

    for (const line of lines) {
        if (/^export interface .+ \{/.test(line)) {
            inInterface = true;
            continue;
        }
        if (!inInterface) continue;
        if (line.trim() === "}") {
            inInterface = false;
            continue;
        }

        const commentMatch = line.match(/^\s*\/\*\*\s*(.+?)\s*\*\/\s*$/);
        if (commentMatch) {
            pendingComment = commentMatch[1];
            continue;
        }

        const fieldMatch = line.match(/^\s+("[^"]+"|[a-zA-Z]\w*)(\?)?:\s*(.+?);\s*$/);
        if (fieldMatch) {
            const rawName = fieldMatch[1]!;
            const name = rawName.startsWith('"') ? rawName.slice(1, -1) : rawName;
            const required = fieldMatch[2] !== "?";
            const type = fieldMatch[3]!.replace(/\|/g, "\\|"); // escape for markdown table
            out.push({ name, type, required, description: pendingComment });
            pendingComment = undefined;
        } else if (line.trim().length > 0 && !line.trim().startsWith("//")) {
            pendingComment = undefined;
        }
    }
    return out;
}

function extractExample(jsDoc: string): string | null {
    const lines = jsDoc.split("\n");
    const exampleStart = lines.findIndex((l) => l.includes("@example"));
    if (exampleStart === -1) return null;
    const body: string[] = [];
    for (let i = exampleStart + 1; i < lines.length; i++) {
        const stripped = lines[i]!.replace(/^\s*\*\s?/, "");
        if (stripped.trim() === "/" || stripped.trim() === "") {
            if (body.length > 0) break;
            continue;
        }
        body.push(stripped);
    }
    return body.join("\n").trimEnd() || null;
}
