// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../../../../index.js";

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         userId: "userId",
 *         body: {
 *             start: "2024-01-15T09:30:00Z"
 *         }
 *     }
 */
export interface CreateForUserTimeEntriesRequest {
    workspaceId: string;
    userId: string;
    body: ClockifyApi.TimeEntryCreate;
}
