// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId"
 *     }
 */
export interface ListInProgressTimeEntriesRequest {
    workspaceId: string;
    page?: number;
    "page-size"?: number;
}
