// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         invoiced: true,
 *         timeEntryIds: ["timeEntryIds"]
 *     }
 */
export interface PatchWorkspacesWorkspaceIdTimeEntriesInvoicedRequest {
    workspaceId: string;
    invoiced: boolean;
    timeEntryIds: string[];
}
