// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         userId: "userId",
 *         timeEntryId: "timeEntryId"
 *     }
 */
export interface PostWorkspacesWorkspaceIdUserUserIdTimeEntriesTimeEntryIdDuplicateRequest {
    workspaceId: string;
    userId: string;
    timeEntryId: string;
}
