// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../../../../index.js";

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         timeEntryId: "timeEntryId",
 *         body: {
 *             start: "2024-01-15T09:30:00Z"
 *         }
 *     }
 */
export interface UpdateTimeEntriesRequest {
    workspaceId: string;
    timeEntryId: string;
    body: ClockifyApi.TimeEntryUpdate;
}
