// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         userId: "userId",
 *         end: "2024-01-15T09:30:00Z"
 *     }
 */
export interface UpdateForUserTimeEntriesRequest {
    workspaceId: string;
    userId: string;
    end: string;
}
