// This file was auto-generated by Fern from our API Definition.

export const GetWorkspaceProjectsRequestUserStatus = {
    Pending: "PENDING",
    Active: "ACTIVE",
    Declined: "DECLINED",
    Inactive: "INACTIVE",
    All: "ALL",
} as const;
export type GetWorkspaceProjectsRequestUserStatus =
    (typeof GetWorkspaceProjectsRequestUserStatus)[keyof typeof GetWorkspaceProjectsRequestUserStatus];
