// This file was auto-generated by Fern from our API Definition.

export const GetWorkspaceProjectsRequestAccess = {
    Public: "PUBLIC",
    Private: "PRIVATE",
} as const;
export type GetWorkspaceProjectsRequestAccess =
    (typeof GetWorkspaceProjectsRequestAccess)[keyof typeof GetWorkspaceProjectsRequestAccess];
