// This file was auto-generated by Fern from our API Definition.

export const ListProjectsRequestClientStatus = {
    Active: "ACTIVE",
    Archived: "ARCHIVED",
    All: "ALL",
} as const;
export type ListProjectsRequestClientStatus =
    (typeof ListProjectsRequestClientStatus)[keyof typeof ListProjectsRequestClientStatus];
