// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../../../index.js";

export interface ListForUserBalancesResponse {
    balances?: ClockifyApi.BalanceBalance[] | undefined;
    count?: number | undefined;
}
