// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         webhookId: "webhookId"
 *     }
 */
export interface GetWebhookByIdRequest {
    workspaceId: string;
    webhookId: string;
}
