// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         addonId: "addonId"
 *     }
 */
export interface ListForAddonWebhooksRequest {
    workspaceId: string;
    addonId: string;
}
