// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         projectId: "projectId"
 *     }
 */
export interface PutWorkspacesWorkspaceIdProjectsProjectIdArchiveRequest {
    workspaceId: string;
    projectId: string;
    archived?: boolean;
}
