// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../../../../index.js";

/**
 * @example
 *     {
 *         workspaceId: "64a687e29ae1f428e7ebe303",
 *         projectId: "5b641568b07987035750505e",
 *         archived: false,
 *         billable: false,
 *         clientId: "9t641568b07987035750704",
 *         color: "#000000",
 *         costRate: {
 *             amount: 20000,
 *             since: "2020-01-01T00:00:00Z"
 *         },
 *         hourlyRate: {
 *             amount: 20000,
 *             since: "2020-01-01T00:00:00Z"
 *         },
 *         isPublic: false,
 *         name: "Software Development",
 *         note: "This is a sample note for the project."
 *     }
 */
export interface UpdateProjectRequest {
    /** Represents a workspace identifier across the system. */
    workspaceId: string;
    /** Represents a project identifier across the system. */
    projectId: string;
    /** Indicates whether project is archived or not. */
    archived?: boolean;
    /** Indicates whether project is billable or not. */
    billable?: boolean;
    /** Represents client identifier across the system. */
    clientId?: string;
    /** Color value in standard RGB hexadecimal format. */
    color?: string;
    costRate?: ClockifyApi.RateRequest;
    hourlyRate?: ClockifyApi.RateRequest;
    /** Indicates whether project is public or not. */
    isPublic?: boolean;
    /** Represents a project name. */
    name?: string;
    /** Represents project note. */
    note?: string;
}
