// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         projectId: "projectId",
 *         amount: 1
 *     }
 */
export interface UpdateCostRateProjectsRequest {
    workspaceId: string;
    projectId: string;
    amount: number;
    since?: string;
    sinceAsInstant?: string;
}
