/* Generated by scripts/generate-error-docs.mjs. Edit docs/error-codes.json, then run make error-docs. */
export interface ClockifyErrorCodeEntry {
    code: string;
    /** False for documented taxonomy with no SDK-observable runtime signal. */
    reachable?: boolean;
    httpStatus: readonly number[];
    retry: boolean;
    surfaces: readonly string[];
    meaning: string;
    recovery: string;
}

export const CLOCKIFY_ERROR_CODES = [
    {
        "code": "invalid_request",
        "httpStatus": [
            400
        ],
        "retry": false,
        "surfaces": [
            "sdk",
            "cli",
            "mcp"
        ],
        "meaning": "The request is malformed, missing required fields, or locally invalid before Clockify accepts it.",
        "recovery": "Fix the request fields, IDs, dates, pagination values, or enum values, then retry.",
        "reachable": true
    },
    {
        "code": "auth_or_permission",
        "httpStatus": [
            401,
            403
        ],
        "retry": false,
        "surfaces": [
            "sdk",
            "cli",
            "mcp"
        ],
        "meaning": "The token is missing, invalid, expired, pointed at the wrong workspace, or lacks permission for the operation.",
        "recovery": "Check CLOCKIFY_API_KEY or addon token, workspace ID, and the user's Clockify role or plan permissions.",
        "reachable": true
    },
    {
        "code": "feature_unavailable",
        "httpStatus": [
            402
        ],
        "retry": false,
        "surfaces": [
            "sdk",
            "cli",
            "mcp"
        ],
        "meaning": "The endpoint exists but the workspace plan or feature configuration does not expose it.",
        "recovery": "Use a supported workspace plan, skip the gated workflow, or fall back to a lower-level read operation.",
        "reachable": true
    },
    {
        "code": "not_found",
        "httpStatus": [
            404
        ],
        "retry": false,
        "surfaces": [
            "sdk",
            "cli",
            "mcp"
        ],
        "meaning": "The requested object does not exist, is archived/deleted, or is outside the active workspace.",
        "recovery": "List the resource again, use returned IDs instead of names, and confirm the workspace ID.",
        "reachable": true
    },
    {
        "code": "conflict",
        "httpStatus": [
            409
        ],
        "retry": false,
        "surfaces": [
            "sdk",
            "cli",
            "mcp"
        ],
        "meaning": "Clockify rejected the write because it conflicts with existing state, uniqueness, or a concurrent update.",
        "recovery": "Fetch current state, reuse the existing object when appropriate, or retry with a different name or payload.",
        "reachable": true
    },
    {
        "code": "rate_limited",
        "httpStatus": [
            429
        ],
        "retry": true,
        "surfaces": [
            "sdk",
            "cli",
            "mcp"
        ],
        "meaning": "Clockify rate-limited the caller.",
        "recovery": "Wait for Retry-After or X-RateLimit-Reset when present; otherwise retry with exponential backoff.",
        "reachable": true
    },
    {
        "code": "clockify_upstream_error",
        "httpStatus": [
            500,
            502,
            503,
            504
        ],
        "retry": true,
        "surfaces": [
            "sdk",
            "cli",
            "mcp"
        ],
        "meaning": "Clockify returned a server-side or temporary upstream failure.",
        "recovery": "Retry idempotent reads/writes with backoff; preserve request IDs for support/debugging.",
        "reachable": true
    },
    {
        "code": "connection_error",
        "httpStatus": [],
        "retry": true,
        "surfaces": [
            "sdk",
            "cli",
            "mcp"
        ],
        "meaning": "The process could not reach Clockify before receiving an HTTP response.",
        "recovery": "Check network, proxy, DNS, TLS, base URL, and retry with backoff.",
        "reachable": true
    },
    {
        "code": "aborted",
        "httpStatus": [],
        "retry": false,
        "surfaces": [
            "sdk",
            "cli",
            "mcp"
        ],
        "meaning": "The caller cancelled the operation with an AbortSignal or equivalent stop request.",
        "recovery": "Do not retry automatically; surface cancellation to the caller.",
        "reachable": true
    },
    {
        "code": "rate_limited_retry_after",
        "httpStatus": [],
        "retry": true,
        "surfaces": [
            "sdk",
            "cli",
            "mcp"
        ],
        "meaning": "Clockify returned 429 with a Retry-After or X-RateLimit-Reset header naming when the caller may resume.",
        "recovery": "Read the Retry-After seconds or X-RateLimit-Reset epoch from response headers, wait that long, then retry the same request once.",
        "reachable": true
    },
    {
        "code": "addon_token_restricted",
        "httpStatus": [],
        "retry": false,
        "surfaces": [
            "sdk",
            "mcp"
        ],
        "meaning": "An X-Addon-Token request reached an endpoint outside the add-on token's allowed surface.",
        "recovery": "Use a user API key for that endpoint, or restrict the add-on workflow to endpoints its token can call.",
        "reachable": true
    },
    {
        "code": "host_routing_required",
        "httpStatus": [],
        "retry": false,
        "surfaces": [
            "sdk",
            "cli",
            "mcp"
        ],
        "meaning": "Reports, audit-log, or expense-report operations were sent to the default API host instead of their dedicated Clockify host.",
        "recovery": "Let the typed SDK method pick its per-operation host, or pass the matching reports/audit-log base URL explicitly.",
        "reachable": false
    },
    {
        "code": "active_resource_delete_blocked",
        "httpStatus": [],
        "retry": false,
        "surfaces": [
            "sdk",
            "cli",
            "mcp"
        ],
        "meaning": "Clockify rejected a bare DELETE of an active project, task, or client before the object could be removed.",
        "recovery": "Archive the project/client first, or mark a task done first, then issue the delete.",
        "reachable": true
    },
    {
        "code": "dead_route",
        "httpStatus": [],
        "retry": false,
        "surfaces": [
            "sdk",
            "cli",
            "mcp"
        ],
        "meaning": "A documented Clockify route is not served and returns a static-resource 404 or equivalent unsupported response.",
        "recovery": "Use the replacement path recorded in the evidence ledger and treat the response as a quarantined route, not a transient missing object.",
        "reachable": false
    },
    {
        "code": "name_reserved_after_delete",
        "httpStatus": [],
        "retry": false,
        "surfaces": [
            "sdk",
            "cli",
            "mcp"
        ],
        "meaning": "A project, tag, or client name stayed reserved briefly after deletion, so an immediate recreate with the same name was rejected.",
        "recovery": "Wait for the reservation window, reuse the existing object when present, or create the new entity with a distinct name.",
        "reachable": false
    },
    {
        "code": "error",
        "httpStatus": [],
        "retry": false,
        "surfaces": [
            "cli",
            "mcp"
        ],
        "meaning": "Unknown local/runtime failure that does not fit a more specific code yet.",
        "recovery": "Preserve the message and request ID if available, then classify the failure into a stable code before broadening behavior.",
        "reachable": true
    },
    {
        "code": "setup_required",
        "httpStatus": [],
        "retry": false,
        "surfaces": [
            "mcp"
        ],
        "meaning": "The MCP server started but required credentials (CLOCKIFY_API_KEY and/or CLOCKIFY_WORKSPACE_ID) are not set, so no Clockify call can be made yet.",
        "recovery": "Set CLOCKIFY_API_KEY and CLOCKIFY_WORKSPACE_ID in the MCP client's env block, then restart the server. Get the API key from Clockify Profile Settings -> API; the workspace ID is in the workspace URL.",
        "reachable": true
    }
] as const satisfies readonly ClockifyErrorCodeEntry[];

export type ClockifyErrorCode = (typeof CLOCKIFY_ERROR_CODES)[number]["code"];

export function errorCodeForStatus(status: number | undefined): ClockifyErrorCode | undefined {
    if (status == null) return undefined;
    return CLOCKIFY_ERROR_CODES.find((entry) => (entry.httpStatus as readonly number[]).includes(status))?.code;
}

export function errorCodeForMessage(message: string): ClockifyErrorCode {
    // A wrong/missing id 400s with a code:501 body like "Project doesn't belong
    // to Workspace" / "... doesn't exist" — that is a not_found, classified BEFORE
    // the auth/invalid matchers so the bare "workspace"/"invalid" tokens can't
    // claim it.
    if (/does(?:n'?t| not) (?:belong to|exist)/i.test(message)) return "not_found";
    if (/(unauthorized|forbidden|permission|api[\s_-]?key|addon[\s_-]?token|CLOCKIFY_API_KEY|CLOCKIFY_ADDON_TOKEN|workspace id not set)/i.test(message)) return "auth_or_permission";
    if (/(required|provide|missing|invalid|unknown option|unknown command|could not parse|not valid|must use|must not|confirmation token)/i.test(message)) {
        return "invalid_request";
    }
    if (/not found/i.test(message)) return "not_found";
    if (/(rate.?limit|too many requests)/i.test(message)) return "rate_limited";
    if (/(network|fetch failed|econnreset|dns|tls)/i.test(message)) return "connection_error";
    if (/(abort|cancel)/i.test(message)) return "aborted";
    return "error";
}

export function errorCodeEntry(code: ClockifyErrorCode): ClockifyErrorCodeEntry {
    return CLOCKIFY_ERROR_CODES.find((entry) => entry.code === code) ?? CLOCKIFY_ERROR_CODES[0];
}

export function recoveryForCode(code: ClockifyErrorCode): string {
    return errorCodeEntry(code).recovery;
}

export function retryableForCode(code: ClockifyErrorCode): boolean {
    return errorCodeEntry(code).retry;
}
