// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         categoryId: "categoryId",
 *         archived: false
 *     }
 */
export interface ExpenseCategoryStatusRequest {
    workspaceId: string;
    categoryId: string;
    /** Flag whether to archive the expense category or not. */
    archived: boolean;
}
