// This file was auto-generated by Fern from our API Definition.

export interface ExportInvoiceRequest {
    workspaceId: string;
    invoiceId: string;
    /** Required by live Clockify invoice export; the MCP defaults it to en-US. */
    userLocale: string;
}
