// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../../../../index.js";

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         clients: {
 *             contains: "CONTAINS",
 *             ids: ["44a687e29ae1f428e7ebe305"],
 *             status: "ACTIVE"
 *         },
 *         companies: {
 *             contains: "CONTAINS",
 *             ids: ["04g687e29ae1f428e7ebe123"]
 *         },
 *         exactAmount: 1000,
 *         exactBalance: 1000,
 *         greaterThanAmount: 500,
 *         greaterThanBalance: 500,
 *         invoiceNumber: "Invoice-01",
 *         issueDate: {
 *             "issue-date-end": "2024-12-31",
 *             "issue-date-start": "2024-01-01"
 *         },
 *         lessThanAmount: 500,
 *         lessThanBalance: 500,
 *         page: 1,
 *         pageSize: 50,
 *         sortColumn: "ID",
 *         sortOrder: "ASCENDING",
 *         statuses: ["SENT", "PAID", "PARTIALLY_PAID"],
 *         strictSearch: false
 *     }
 */
export interface InvoiceFilterRequest {
    workspaceId: string;
    clients?: ClockifyApi.ContainsArchivedFilterRequest;
    companies?: ClockifyApi.BaseFilterRequest;
    /** If provided, filters invoices with the exact amount. */
    exactAmount?: number;
    /** If provided, filters invoices with the exact balance. */
    exactBalance?: number;
    /** If provided, filters invoices with amount greater than specified. */
    greaterThanAmount?: number;
    /** If provided, filters invoices with balance greater than specified. */
    greaterThanBalance?: number;
    /** If provided, filters invoices that contain the provided string in their invoice number. */
    invoiceNumber?: string;
    issueDate?: ClockifyApi.TimeRangeRequestDtoV1;
    /** If provided, filters invoices with amount less than specified. */
    lessThanAmount?: number;
    /** If provided, filters invoices with balance less than specified. */
    lessThanBalance?: number;
    /** Page number. */
    page?: number;
    /** Page size. */
    pageSize?: number;
    sortColumn?: ClockifyApi.InvoiceSortColumn;
    sortOrder?: ClockifyApi.InvoicesSortOrder;
    /** Represents a list of invoice statuses. */
    statuses?: ClockifyApi.InvoiceStatus[];
    /** When true, search by invoice number only returns invoices whose number exactly matches the provided string. */
    strictSearch?: boolean;
}
