// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../../../../index.js";

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         invoiceId: "invoiceId",
 *         clientId: "98h687e29ae1f428e7ebe707",
 *         companyId: "04g687e29ae1f428e7ebe123",
 *         currency: "USD",
 *         discountPercent: 10.5,
 *         dueDate: "2020-06-01T08:00:00Z",
 *         issuedDate: "2020-01-01T08:00:00Z",
 *         note: "This is a sample note for this invoice.",
 *         number: "202306121129",
 *         subject: "January salary",
 *         tax2Percent: 0,
 *         taxPercent: 1.5,
 *         taxType: "SIMPLE",
 *         visibleZeroFields: ["TAX", "TAX_2", "DISCOUNT"]
 *     }
 */
export interface UpdateInvoiceRequest {
    workspaceId: string;
    invoiceId: string;
    /** Represents client identifier across the system. */
    clientId?: string;
    /** Represents company identifier across the system. */
    companyId?: string;
    /** Represents the currency used by the invoice. */
    currency: string;
    /** Represents an invoice discount percent as double. */
    discountPercent: number;
    /** Represents an invoice due date in yyyy-MM-ddThh:mm:ssZ format. */
    dueDate: string;
    /** Represents an invoice issued date in yyyy-MM-ddThh:mm:ssZ format. */
    issuedDate: string;
    /** Represents an invoice note. */
    note?: string;
    /** Represents an invoice number. */
    number: string;
    /** Represents an invoice subject. */
    subject?: string;
    /** Represents an invoice tax 2 percent as double. */
    tax2Percent: number;
    /** Represents an invoice tax percent as double. */
    taxPercent: number;
    taxType?: ClockifyApi.TaxType;
    /** Represents one or more zero value invoice fields that will be visible. */
    visibleZeroFields?: UpdateInvoiceRequest.VisibleZeroFields;
}

export namespace UpdateInvoiceRequest {
    /**
     * Represents one or more zero value invoice fields that will be visible.
     */
    export type VisibleZeroFields = ClockifyApi.VisibleZeroFieldsInvoice | ClockifyApi.VisibleZeroFieldsInvoice[];
}
