// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../../../../index.js";

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         projectId: "projectId",
 *         assigneeIds: ["45b687e29ae1f428e7ebe123", "67s687e29ae1f428e7ebe678"],
 *         budgetEstimate: 10000,
 *         estimate: "PT1H30M",
 *         id: "57a687e29ae1f428e7ebe107",
 *         name: "Bugfixing",
 *         status: "DONE",
 *         userGroupIds: ["67b687e29ae1f428e7ebe123", "12s687e29ae1f428e7ebe678"]
 *     }
 */
export interface TaskCreateRequest {
    workspaceId: string;
    projectId: string;
    /** Deprecated task assignee identifier. */
    assigneeId?: string;
    /** Represents list of assignee ids for the task. */
    assigneeIds?: string[];
    /** Represents a task budget estimate as long. */
    budgetEstimate?: number;
    /** Represents a task duration estimate in ISO-8601 format. */
    estimate?: string;
    /** Represents task identifier across the system. */
    id?: string;
    /** Represents task name. */
    name: string;
    status?: ClockifyApi.TaskStatus;
    /** Represents list of user group ids for the task. */
    userGroupIds?: string[];
}
