// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../../../../index.js";

/**
 * @example
 *     {
 *         workspaceId: "workspaceId",
 *         projectId: "projectId",
 *         taskId: "taskId",
 *         body: {
 *             amount: 20000,
 *             since: "2020-01-01T00:00:00Z"
 *         }
 *     }
 */
export interface UpdateBillableRateTasksRequest {
    workspaceId: string;
    projectId: string;
    taskId: string;
    body: ClockifyApi.RateUpdateRequest;
}
