// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

export interface AmountDto {
    type?: ClockifyApi.AmountType | undefined;
    /** Amount value. */
    value?: number | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
