// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Represents a valid approval request data transfer object.
 */
export interface ApprovalRequestDtoV1 {
    creator?: ClockifyApi.ApprovalRequestCreatorDtoV1 | undefined;
    dateRange?: ClockifyApi.DateRangeDto | undefined;
    /** Represents approval request identifier across the workspace. */
    id?: string | undefined;
    owner?: ClockifyApi.ApprovalRequestOwnerDtoV1 | undefined;
    status?: ClockifyApi.ApprovalRequestStatusDtoV1 | undefined;
    /** Represents workspace identifier across the system. */
    workspaceId?: string | undefined;
}
