// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

export interface ApprovalRequestListItem {
    approvalRequest?: ClockifyApi.ApprovalRequestDtoV1 | undefined;
    approvedTime?: ClockifyApi.DurationString | undefined;
    billableAmount?: number | undefined;
    billableTime?: ClockifyApi.DurationString | undefined;
    breakTime?: ClockifyApi.DurationString | undefined;
    /** Represents an amount. */
    costAmount?: number | undefined;
    /** Represents a list of time entry info data transfer objects. */
    entries?: ClockifyApi.TimeEntryInfoDto[] | undefined;
    /** Represents an amount. */
    expenseTotal?: number | undefined;
    /** Represents a list of expense hydrated data transfer objects. */
    expenses?: ClockifyApi.ExpenseHydratedDto[] | undefined;
    pendingTime?: ClockifyApi.DurationString | undefined;
    trackedTime?: ClockifyApi.DurationString | undefined;
}
