// This file was auto-generated by Fern from our API Definition.

export const ApprovalRequestSortColumn = {
    Id: "ID",
    UserId: "USER_ID",
    Start: "START",
    UpdatedAt: "UPDATED_AT",
} as const;
export type ApprovalRequestSortColumn = (typeof ApprovalRequestSortColumn)[keyof typeof ApprovalRequestSortColumn];
