// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Attendance report response.
 */
export interface AttendanceReportResponse {
    /** List of attendance report entities. */
    entities?: ClockifyApi.AttendanceDto[] | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
