// This file was auto-generated by Fern from our API Definition.

/**
 * Minimal audit log entry shape observed from the audit-log service.
 */
export interface AuditLogEntry {
    action?: string | undefined;
    content?: (string | null) | undefined;
    previousContent?: (string | null) | undefined;
    timestamp?: string | undefined;
    userEmail?: string | undefined;
    userId?: string | undefined;
    userName?: string | undefined;
    workspaceId?: string | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
