// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Provides automatic time entry creation settings.
 */
export interface AutomaticTimeEntryCreationRequest {
    defaultEntities: ClockifyApi.PoliciesDefaultEntitiesRequest;
    /** Indicates that automatic time entry creation is enabled. */
    enabled?: boolean | undefined;
}
