// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Represents automatic time entry creation settings.
 */
export interface AutomaticTimeEntryCreationDto {
    defaultEntities?: ClockifyApi.DefaultEntitiesDto | undefined;
    enabled?: boolean | undefined;
}
