// This file was auto-generated by Fern from our API Definition.

export interface BalanceBalance {
    balance?: number | undefined;
    id?: string | undefined;
    policyId?: string | undefined;
    policyName?: string | undefined;
    policyTimeUnit?: string | undefined;
    total?: number | undefined;
    used?: number | undefined;
    userId?: string | undefined;
    userName?: string | undefined;
    workspaceId?: string | undefined;
}
