// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Paginated balance list response.
 */
export interface BalanceListResponse {
    /** List of balances. */
    balances?: ClockifyApi.BalanceDtoV1[] | undefined;
    /** Represents the count of balances. */
    count?: number | undefined;
}
