// This file was auto-generated by Fern from our API Definition.

/** Valid column for sorting balance results. */
export const BalanceSortColumn = {
    User: "USER",
    Policy: "POLICY",
    Used: "USED",
    Balance: "BALANCE",
    Total: "TOTAL",
} as const;
export type BalanceSortColumn = (typeof BalanceSortColumn)[keyof typeof BalanceSortColumn];
