// This file was auto-generated by Fern from our API Definition.

export interface Balance {
    balance?: number | undefined;
    carriedOver?: number | undefined;
    period?: Balance.Period | undefined;
    policyId?: string | undefined;
    usedThisPeriod?: number | undefined;
    userId?: string | undefined;
}

export namespace Balance {
    export interface Period {
        end?: string | undefined;
        start?: string | undefined;
    }
}
