// This file was auto-generated by Fern from our API Definition.

/**
 * LIVE VERIFICATION REVEALED - Field 'end' is mandatory for bulk edits on live system, contrary to single-update documentation.
 */
export interface BulkEditTimeEntryRequest {
    billable?: boolean | undefined;
    description?: string | undefined;
    end: string;
    id: string;
    projectId?: string | undefined;
    start: string;
    taskId?: string | undefined;
}
