// This file was auto-generated by Fern from our API Definition.

/** Represents whether tax is calculated as item based or invoice based. */
export const CalculationType = {
    InvoiceBased: "INVOICE_BASED",
    ItemBased: "ITEM_BASED",
} as const;
export type CalculationType = (typeof CalculationType)[keyof typeof CalculationType];
