// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

export interface ClientCreate {
    address?: string | undefined;
    currencyCode?: ClockifyApi.Currency | undefined;
    email?: string | undefined;
    name: string;
    note?: string | undefined;
}
