// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

export interface Client {
    address?: (string | null) | undefined;
    archived?: boolean | undefined;
    currencyCode?: ClockifyApi.Currency | undefined;
    email?: (string | null) | undefined;
    id?: string | undefined;
    name?: string | undefined;
    note?: (string | null) | undefined;
    workspaceId?: string | undefined;
}
