// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Represents a filter for imported items that can include archived entities.
 */
export interface ContainsArchivedFilterRequest {
    contains?: ClockifyApi.ContainsOperator | undefined;
    /** Represents a list of filter identifiers. */
    ids?: string[] | undefined;
    status?: ClockifyApi.EntityStatus | undefined;
}
