// This file was auto-generated by Fern from our API Definition.

/**
 * Filter by contained archived-aware entities.
 */
export interface ContainsArchivedFilter {
    /** Represents a contains type. */
    contains?: ContainsArchivedFilter.Contains | undefined;
    /** Filter includes the provided list of ids. */
    ids?: string[] | undefined;
    /** Filter entities by status. */
    status?: ContainsArchivedFilter.Status | undefined;
}

export namespace ContainsArchivedFilter {
    /** Represents a contains type. */
    export const Contains = {
        Contains: "CONTAINS",
        DoesNotContain: "DOES_NOT_CONTAIN",
        ContainsOnly: "CONTAINS_ONLY",
    } as const;
    export type Contains = (typeof Contains)[keyof typeof Contains];
    /** Filter entities by status. */
    export const Status = {
        Active: "ACTIVE",
        Archived: "ARCHIVED",
        All: "ALL",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
