// This file was auto-generated by Fern from our API Definition.

/**
 * Provide list with user ids and corresponding status.
 */
export interface ContainsUsersFilterRequestForHoliday {
    /** Filter type. */
    contains?: ContainsUsersFilterRequestForHoliday.Contains | undefined;
    /** Represents a list of filter identifiers. */
    ids?: string[] | undefined;
    /** Filters entities by status. */
    status?: ContainsUsersFilterRequestForHoliday.Status | undefined;
    statuses?: string[] | undefined;
}

export namespace ContainsUsersFilterRequestForHoliday {
    /** Filter type. */
    export const Contains = {
        Contains: "CONTAINS",
        DoesNotContain: "DOES_NOT_CONTAIN",
        ContainsOnly: "CONTAINS_ONLY",
    } as const;
    export type Contains = (typeof Contains)[keyof typeof Contains];
    /** Filters entities by status. */
    export const Status = {
        All: "ALL",
        Active: "ACTIVE",
        Inactive: "INACTIVE",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
