// This file was auto-generated by Fern from our API Definition.

/** Filter type. */
export const ContainsOperator = {
    Contains: "CONTAINS",
    DoesNotContain: "DOES_NOT_CONTAIN",
    ContainsOnly: "CONTAINS_ONLY",
} as const;
export type ContainsOperator = (typeof ContainsOperator)[keyof typeof ContainsOperator];
