// This file was auto-generated by Fern from our API Definition.

/**
 * Represents a custom field default values object.
 */
export interface CustomFieldDefaultValuesDtoV1 {
    /** Represents project identifier across the system. */
    projectId?: string | undefined;
    /** Represents custom field status. */
    status?: string | undefined;
    /** Represents a custom field's default value. */
    value?: (unknown | null) | undefined;
}
