// This file was auto-generated by Fern from our API Definition.

/** Custom field status. */
export const CustomFieldStatus = {
    Inactive: "INACTIVE",
    Visible: "VISIBLE",
    Invisible: "INVISIBLE",
} as const;
export type CustomFieldStatus = (typeof CustomFieldStatus)[keyof typeof CustomFieldStatus];
