// This file was auto-generated by Fern from our API Definition.

/**
 * Represents a custom field value object.
 */
export interface CustomFieldValueDto {
    /** Represents custom field identifier across the system. */
    customFieldId?: string | undefined;
    /** Represents a custom field value source type. */
    sourceType?: CustomFieldValueDto.SourceType | undefined;
    /** Represents time entry identifier across the system. */
    timeEntryId?: string | undefined;
    /** Represents custom field value. */
    value?: unknown | undefined;
}

export namespace CustomFieldValueDto {
    /** Represents a custom field value source type. */
    export const SourceType = {
        Workspace: "WORKSPACE",
        Project: "PROJECT",
        Timeentry: "TIMEENTRY",
    } as const;
    export type SourceType = (typeof SourceType)[keyof typeof SourceType];
}
