// This file was auto-generated by Fern from our API Definition.

/**
 * Custom field filter.
 */
export interface CustomFieldFilter {
    /** Represents a custom field identifier across the system. */
    id?: string | undefined;
    /** Indicates whether the custom field is empty. */
    isEmpty?: boolean | undefined;
    /** Represents a custom field number condition. */
    numberCondition?: CustomFieldFilter.NumberCondition | undefined;
    /** Represents a type of custom field. */
    type?: CustomFieldFilter.Type | undefined;
    /** Represents a custom field value. The value type depends on the custom field type. */
    value?: CustomFieldFilter.Value | undefined;
}

export namespace CustomFieldFilter {
    /** Represents a custom field number condition. */
    export const NumberCondition = {
        Equal: "EQUAL",
        GreaterThan: "GREATER_THAN",
        LessThan: "LESS_THAN",
    } as const;
    export type NumberCondition = (typeof NumberCondition)[keyof typeof NumberCondition];
    /** Represents a type of custom field. */
    export const Type = {
        Txt: "TXT",
        Number: "NUMBER",
        DropdownSingle: "DROPDOWN_SINGLE",
        DropdownMultiple: "DROPDOWN_MULTIPLE",
        Checkbox: "CHECKBOX",
        Link: "LINK",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    /**
     * Represents a custom field value. The value type depends on the custom field type.
     */
    export type Value = string | number | boolean | unknown[] | Record<string, unknown>;
}
