// This file was auto-generated by Fern from our API Definition.

/**
 * Represents date range object.
 */
export interface DateRangeDto {
    end?: string | undefined;
    start?: string | undefined;
}
