// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Detailed report response. Both timeEntries and timeentries are valid payload keys.
 */
export interface DetailedReportResponse {
    /** List of time entries. */
    timeEntries?: ClockifyApi.TimeEntryDto[] | undefined;
    /** Lowercase alias for timeEntries. Included so both payload spellings validate. */
    timeentries?: ClockifyApi.TimeEntryDto[] | undefined;
    /** List of report totals. */
    totals?: ClockifyApi.TimeEntryReportTotals[] | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
