// This file was auto-generated by Fern from our API Definition.

/**
 * Represents an entity creation permission enum with optional creators.
 */
export interface EntityCreationPermission {
    creators?: string[] | undefined;
    value?: EntityCreationPermission.Value | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace EntityCreationPermission {
    export const Value = {
        Admins: "ADMINS",
        AdminsAndProjectManagers: "ADMINS_AND_PROJECT_MANAGERS",
        Everyone: "EVERYONE",
    } as const;
    export type Value = (typeof Value)[keyof typeof Value];
}
