// This file was auto-generated by Fern from our API Definition.

/**
 * Represents estimate reset request object.
 */
export interface EstimateResetRequest {
    active?: boolean | undefined;
    /** Represents a day of the month. */
    dayOfMonth?: number | undefined;
    /** Represents a day of the week. */
    dayOfWeek?: EstimateResetRequest.DayOfWeek | undefined;
    /** Represents an hour of the day in 24-hour time format. */
    hour?: number | undefined;
    /** Represents a reset option enum. */
    interval?: EstimateResetRequest.Interval | undefined;
    isActive?: boolean | undefined;
    /** Represents a month enum. */
    month?: EstimateResetRequest.Month | undefined;
}

export namespace EstimateResetRequest {
    /** Represents a day of the week. */
    export const DayOfWeek = {
        Monday: "MONDAY",
        Tuesday: "TUESDAY",
        Wednesday: "WEDNESDAY",
        Thursday: "THURSDAY",
        Friday: "FRIDAY",
        Saturday: "SATURDAY",
        Sunday: "SUNDAY",
    } as const;
    export type DayOfWeek = (typeof DayOfWeek)[keyof typeof DayOfWeek];
    /** Represents a reset option enum. */
    export const Interval = {
        Weekly: "WEEKLY",
        Monthly: "MONTHLY",
        Yearly: "YEARLY",
    } as const;
    export type Interval = (typeof Interval)[keyof typeof Interval];
    /** Represents a month enum. */
    export const Month = {
        January: "JANUARY",
        February: "FEBRUARY",
        March: "MARCH",
        April: "APRIL",
        May: "MAY",
        June: "JUNE",
        July: "JULY",
        August: "AUGUST",
        September: "SEPTEMBER",
        October: "OCTOBER",
        November: "NOVEMBER",
        December: "DECEMBER",
    } as const;
    export type Month = (typeof Month)[keyof typeof Month];
}
