// This file was auto-generated by Fern from our API Definition.

/**
 * Represents a project estimate object.
 */
export interface EstimateDtoV1 {
    /** Represents a task duration estimate. */
    estimate?: string | undefined;
    /** Represents an estimate type enum. */
    type?: EstimateDtoV1.Type | undefined;
}

export namespace EstimateDtoV1 {
    /** Represents an estimate type enum. */
    export const Type = {
        Auto: "AUTO",
        Manual: "MANUAL",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
