// This file was auto-generated by Fern from our API Definition.

/**
 * Represents expense totals
 */
export interface ExpenseTotalsDtoV1 {
    /** Represents expenses count */
    expensesCount?: number | undefined;
    /** Represents total amount of expenses */
    totalAmount?: number | undefined;
    /** Represents total billable amount of expenses */
    totalAmountBillable?: number | undefined;
}
