// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Hydrated expense object. The uploaded Markdown names ExpenseHydratedDtoV1 but does not enumerate fields beyond the standard expense sample.
 */
export type ExpenseHydratedDtoV1 = ClockifyApi.ExpenseDtoV1;
