// This file was auto-generated by Fern from our API Definition.

export interface ExpenseCategoryDto {
    archived?: boolean | undefined;
    hasUnitPrice?: boolean | undefined;
    id?: string | undefined;
    name?: string | undefined;
    priceInCents?: number | undefined;
    unit?: string | undefined;
    workspaceId?: string | undefined;
}
