// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * report
 */
export interface ExpenseDetailedReportDtoV1 {
    /** Represents list of expenses */
    expenses?: ClockifyApi.ExpenseReportDtoV1[] | undefined;
    totals?: ClockifyApi.ExpenseTotalsDtoV1 | undefined;
}
