// This file was auto-generated by Fern from our API Definition.

export const ExpensesGroupBy = {
    Category: "CATEGORY",
    Project: "PROJECT",
    User: "USER",
} as const;
export type ExpensesGroupBy = (typeof ExpensesGroupBy)[keyof typeof ExpensesGroupBy];
