// This file was auto-generated by Fern from our API Definition.

/**
 * Represents an expense daily total data transfer object.
 */
export interface ExpenseDailyTotalsDtoV1 {
    /** Date in yyyy-MM-dd format. */
    date?: string | undefined;
    dateAsInstant?: string | undefined;
    /** Represents expense total. */
    total?: number | undefined;
}
