// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Expense categories list response.
 */
export interface ExpenseCategoriesDtoV1 {
    categories?: ClockifyApi.ExpenseCategoryDtoV1[] | undefined;
    /** Represents the number of categories returned. */
    count?: number | undefined;
}
