// This file was auto-generated by Fern from our API Definition.

/**
 * Represents an expense object.
 */
export interface ExpenseDtoV1 {
    /** Indicates whether expense is billable or not. */
    billable?: boolean | undefined;
    /** Represents category identifier across the system. */
    categoryId?: string | undefined;
    /** Represents a date in yyyy-MM-dd format. */
    date?: string | undefined;
    /** Represents file identifier across the system. */
    fileId?: string | undefined;
    /** Represents expense identifier across the system. */
    id?: string | undefined;
    /** Indicates whether the expense is locked. */
    locked?: boolean | undefined;
    /** Represents notes for an expense. */
    notes?: string | undefined;
    /** Represents project identifier across the system. */
    projectId?: string | undefined;
    /**
     * Represents expense quantity as double data type.
     * Create/update requests use amount; live expense responses expose the entered amount as quantity and the computed value as total.
     */
    quantity?: number | undefined;
    /** Represents task identifier across the system. */
    taskId?: string | undefined;
    /** Represents expense total as double data type. */
    total?: number | undefined;
    /** Represents user identifier across the system. */
    userId?: string | undefined;
    /** Represents workspace identifier across the system. */
    workspaceId?: string | undefined;
}
