// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

export interface GroupOneDto {
    /** Group amount. */
    amount?: number | undefined;
    /** Nested child groups. */
    children?: ClockifyApi.GroupOneDto[] | undefined;
    /** Client name. */
    clientName?: string | undefined;
    /** Daily totals for the group. */
    days?: ClockifyApi.DailyTotalDto[] | undefined;
    /** Duration. */
    duration?: number | undefined;
    /** Group identifier. */
    id?: string | undefined;
    /** Name. */
    name?: string | undefined;
    /** Lowercase name. */
    nameLowerCase?: string | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
