// This file was auto-generated by Fern from our API Definition.

/** Represents the half day period. */
export const HalfDayPeriod = {
    FirstHalf: "FIRST_HALF",
    SecondHalf: "SECOND_HALF",
    NotDefined: "NOT_DEFINED",
} as const;
export type HalfDayPeriod = (typeof HalfDayPeriod)[keyof typeof HalfDayPeriod];
