// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Represents a holiday with detailed user and user group assignments.
 */
export interface HolidayDetailsDto {
    automaticTimeEntryCreation?: ClockifyApi.AutomaticTimeEntryCreationDto | undefined;
    /** Color value in standard RGB hexadecimal format. */
    color?: string | undefined;
    datePeriod?: ClockifyApi.DatePeriod | undefined;
    /** Indicates whether the holiday is shown to new users. */
    everyoneIncludingNew?: boolean | undefined;
    /** Represents holiday identifier across the system. */
    id?: string | undefined;
    /** Represents the name of the holiday. */
    name?: string | undefined;
    /** Indicates whether the holiday occurs annually. */
    occursAnnually?: boolean | undefined;
    /** Indicates which user groups are included. */
    userGroupIds?: string[] | undefined;
    /** Contains names of user groups that are assigned to holiday. */
    userGroups?: ClockifyApi.EntityIdNameDto[] | undefined;
    /** Indicates which users are included. */
    userIds?: string[] | undefined;
    /** Contains names of users that are assigned to holiday. */
    users?: ClockifyApi.EntityIdNameDto[] | undefined;
    /** Represents workspace identifier across the system. */
    workspaceId?: string | undefined;
}
