// This file was auto-generated by Fern from our API Definition.

/** Represents the live status of an invoice. DRAFT is rejected by Clockify; use UNSENT for draft-like invoices. */
export const InvoiceStatus = {
    Unsent: "UNSENT",
    Sent: "SENT",
    Paid: "PAID",
    PartiallyPaid: "PARTIALLY_PAID",
    Void: "VOID",
    Overdue: "OVERDUE",
} as const;
export type InvoiceStatus = (typeof InvoiceStatus)[keyof typeof InvoiceStatus];
