// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Represents a complete invoice object.
 */
export interface InvoiceDtoFull {
    /** Represents an invoice amount as long. */
    amount?: number | undefined;
    /** Represents an invoice balance amount as long. */
    balance?: number | undefined;
    /** Represents to whom the invoice should be billed from. */
    billFrom?: string | undefined;
    calculationType?: ClockifyApi.CalculationType | undefined;
    /** Represents client address. */
    clientAddress?: string | undefined;
    /** Represents client identifier across the system. */
    clientId?: string | undefined;
    /** Represents client name for an invoice. */
    clientName?: string | undefined;
    /** Represents company identifier across the system. */
    companyId?: string | undefined;
    /** Indicates whether invoice contains imported expenses. */
    containsImportedExpenses?: boolean | undefined;
    /** Indicates whether invoice contains imported items. */
    containsImportedTimes?: boolean | undefined;
    /** Represents the currency used by the invoice. */
    currency?: string | undefined;
    /** Represents an invoice discount amount as double. */
    discount?: number | undefined;
    /** Represents an invoice discount amount as long. */
    discountAmount?: number | undefined;
    /** Represents an invoice due date in yyyy-MM-ddThh:mm:ssZ format. */
    dueDate?: string | undefined;
    /** Represents invoice identifier across the system. */
    id?: string | undefined;
    /** Represents an invoice issued date in yyyy-MM-ddThh:mm:ssZ format. */
    issuedDate?: string | undefined;
    /** Represents a list of invoice item datatransfer objects. */
    items?: ClockifyApi.InvoiceItemDto[] | undefined;
    /** Represents an invoice note. */
    note?: string | undefined;
    /** Represents an invoice number. */
    number?: string | undefined;
    /** Represents an invoice paid amount as long. */
    paid?: number | undefined;
    status?: ClockifyApi.InvoiceStatus | undefined;
    /** Represents an invoice subject. */
    subject?: string | undefined;
    /** Represents an invoice subtotal as long. */
    subtotal?: number | undefined;
    /** Represents an invoice tax amount as double. */
    tax?: number | undefined;
    /** Represents an invoice tax amount as double. */
    tax2?: number | undefined;
    /** Represents an invoice tax amount as long. */
    tax2Amount?: number | undefined;
    /** Represents an invoice tax amount as long. */
    taxAmount?: number | undefined;
    taxType?: ClockifyApi.TaxType | undefined;
    /** Represents user identifier across the system. */
    userId?: string | undefined;
    /** Represents a list of zero value invoice fields that will be visible. */
    visibleZeroFields?: ClockifyApi.VisibleZeroFieldsInvoice[] | undefined;
}
