// This file was auto-generated by Fern from our API Definition.

/**
 * Request body used to add or remove a user's manager role.
 */
export interface ManagerRoleRequest {
    /** Represents an entity identifier across the system. */
    entityId: string;
    /** Represents a valid role. */
    role: ManagerRoleRequest.Role;
    /** Optional field used to indicate that the target of the operation is a user group. */
    sourceType?: ManagerRoleRequest.SourceType | undefined;
}

export namespace ManagerRoleRequest {
    /** Represents a valid role. */
    export const Role = {
        WorkspaceAdmin: "WORKSPACE_ADMIN",
        TeamManager: "TEAM_MANAGER",
        ProjectManager: "PROJECT_MANAGER",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
    /** Optional field used to indicate that the target of the operation is a user group. */
    export const SourceType = {
        UserGroup: "USER_GROUP",
    } as const;
    export type SourceType = (typeof SourceType)[keyof typeof SourceType];
}
