// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Represents a membership request object.
 */
export interface MembershipRequest {
    hourlyRate?: ClockifyApi.RateRequest | undefined;
    membershipStatus?: MembershipRequest.MembershipStatus | undefined;
    membershipType?: MembershipRequest.MembershipType | undefined;
    /** Represents user identifier across the system. */
    userId?: string | undefined;
}

export namespace MembershipRequest {
    export const MembershipStatus = {
        Pending: "PENDING",
        Active: "ACTIVE",
        Declined: "DECLINED",
        Inactive: "INACTIVE",
        All: "ALL",
    } as const;
    export type MembershipStatus = (typeof MembershipStatus)[keyof typeof MembershipStatus];
    export const MembershipType = {
        Workspace: "WORKSPACE",
        Project: "PROJECT",
        Usergroup: "USERGROUP",
    } as const;
    export type MembershipType = (typeof MembershipType)[keyof typeof MembershipType];
}
