// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Represents a membership object.
 */
export interface MembershipDtoV1 {
    costRate?: ClockifyApi.RateDtoV1 | undefined;
    hourlyRate?: ClockifyApi.RateDtoV1 | undefined;
    /** Represents a membership status enum. */
    membershipStatus?: MembershipDtoV1.MembershipStatus | undefined;
    /** Represents membership type enum. */
    membershipType?: MembershipDtoV1.MembershipType | undefined;
    /** Represents target identifier across the system. */
    targetId?: string | undefined;
    /** Represents user identifier across the system. */
    userId?: string | undefined;
}

export namespace MembershipDtoV1 {
    /** Represents a membership status enum. */
    export const MembershipStatus = {
        Pending: "PENDING",
        Active: "ACTIVE",
        Declined: "DECLINED",
        Inactive: "INACTIVE",
        All: "ALL",
    } as const;
    export type MembershipStatus = (typeof MembershipStatus)[keyof typeof MembershipStatus];
    /** Represents membership type enum. */
    export const MembershipType = {
        Workspace: "WORKSPACE",
        Project: "PROJECT",
        Usergroup: "USERGROUP",
    } as const;
    export type MembershipType = (typeof MembershipType)[keyof typeof MembershipType];
}
