// This file was auto-generated by Fern from our API Definition.

/**
 * VERIFIED: only `detailedFilter` accepted on detailed endpoint.
 */
export interface OpenapiDetailedFilter {
    auditFilter?: Record<string, unknown> | undefined;
    options?: Record<string, unknown> | undefined;
    page?: number | undefined;
    pageSize?: number | undefined;
    sortColumn?: string | undefined;
    sortOrder?: OpenapiDetailedFilter.SortOrder | undefined;
}

export namespace OpenapiDetailedFilter {
    export const SortOrder = {
        Ascending: "ASCENDING",
        Descending: "DESCENDING",
    } as const;
    export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder];
}
