// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

export interface OpenapiRateDto {
    /** Rate in minor units (cents). e.g. 12000 = 120.00 */
    amount?: number | undefined;
    currency?: ClockifyApi.Currency | undefined;
}
