// This file was auto-generated by Fern from our API Definition.

/**
 * Represents an invoice default settings object.
 */
export interface OpenapiInvoiceDefaultSettingsDto {
    /** Represents company identifier across the system. */
    companyId?: string | undefined;
    /** Represents item type identifier across the system. */
    defaultImportExpenseItemTypeId?: string | undefined;
    /** Represents item type identifier across the system. */
    defaultImportTimeItemTypeId?: string | undefined;
    /** Represents an invoice number of due days. */
    dueDays?: number | undefined;
    itemType?: string | undefined;
    /** Represents item type identifier across the system. */
    itemTypeId?: string | undefined;
    /** Represents an invoice note. */
    notes?: string | undefined;
    /** Represents an invoice subject. */
    subject?: string | undefined;
    tax?: number | undefined;
    tax2?: number | undefined;
    /** Represents a tax amount in percentage. */
    tax2Percent?: number | undefined;
    /** Represents a tax amount in percentage. */
    taxPercent?: number | undefined;
    /** Represents a tax type. */
    taxType?: OpenapiInvoiceDefaultSettingsDto.TaxType | undefined;
}

export namespace OpenapiInvoiceDefaultSettingsDto {
    /** Represents a tax type. */
    export const TaxType = {
        Compound: "COMPOUND",
        Simple: "SIMPLE",
        None: "NONE",
    } as const;
    export type TaxType = (typeof TaxType)[keyof typeof TaxType];
}
