// This file was auto-generated by Fern from our API Definition.

/**
 * Represents a period with date-time start and end values.
 */
export interface Period {
    end?: string | undefined;
    start?: string | undefined;
}
