// This file was auto-generated by Fern from our API Definition.

/**
 * Represents policy approval settings.
 */
export interface PolicyApprovalDto {
    /** Indicates whether approval is required. */
    requiresApproval?: boolean | undefined;
    /** Indicates whether specific members are required to approve. */
    specificMembers?: boolean | undefined;
    /** Indicates whether team manager's approval is required. */
    teamManagers?: boolean | undefined;
    /** Set of user identifiers across the system. */
    userIds?: string[] | undefined;
}
