// This file was auto-generated by Fern from our API Definition.

/**
 * User filter with identifiers and status.
 */
export interface PoliciesUserIdsSchema {
    contains?: PoliciesUserIdsSchema.Contains | undefined;
    /** Identifiers used for filtering. */
    ids?: string[] | undefined;
    /** Represents user status. */
    status?: PoliciesUserIdsSchema.Status | undefined;
}

export namespace PoliciesUserIdsSchema {
    export const Contains = {
        Contains: "CONTAINS",
        DoesNotContain: "DOES_NOT_CONTAIN",
    } as const;
    export type Contains = (typeof Contains)[keyof typeof Contains];
    /** Represents user status. */
    export const Status = {
        All: "ALL",
        Active: "ACTIVE",
        Inactive: "INACTIVE",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
