// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Represents a Clockify project.
 */
export interface Project {
    /** Indicates whether project is archived or not. */
    archived?: boolean | undefined;
    /** Indicates whether project is billable or not. */
    billable?: boolean | undefined;
    budgetEstimate?: ClockifyApi.EstimateWithOptionsDto | undefined;
    /** Represents client identifier across the system. */
    clientId?: string | undefined;
    /** Represents client name. */
    clientName?: string | undefined;
    /** Color value in standard RGB hexadecimal format. */
    color?: string | undefined;
    costRate?: ClockifyApi.RateDtoV1 | undefined;
    /** Represents project duration in milliseconds. */
    duration?: string | undefined;
    estimate?: ClockifyApi.EstimateDtoV1 | undefined;
    estimateReset?: ClockifyApi.EstimateResetDto | undefined;
    hourlyRate?: ClockifyApi.RateDtoV1 | undefined;
    /** Represents project identifier across the system. */
    id?: string | undefined;
    /** Represents a list of membership objects. */
    memberships?: ClockifyApi.MembershipDtoV1[] | undefined;
    /** Represents a project name. */
    name?: string | undefined;
    /** Represents project note. */
    note?: string | undefined;
    /** Indicates whether project is public or not. */
    public?: boolean | undefined;
    /** Indicates whether project is a template or not. */
    template?: boolean | undefined;
    timeEstimate?: ClockifyApi.TimeEstimateDto | undefined;
    /** Represents workspace identifier across the system. */
    workspaceId?: string | undefined;
}
