// This file was auto-generated by Fern from our API Definition.

export interface RateUpdateRequest {
    /** Represents an amount as integer. */
    amount: number;
    /** Represents a date and time in yyyy-MM-ddThh:mm:ssZ format. */
    since?: string | undefined;
}
