// This file was auto-generated by Fern from our API Definition.

/**
 * Represents recurring assignment object.
 */
export interface RecurringAssignmentDto {
    /** Indicates whether assignment is recurring or not. */
    repeat?: boolean | undefined;
    /** Represents series identifier. */
    seriesId?: string | undefined;
    /** Represents number of weeks for this assignment. */
    weeks?: number | undefined;
}
