// This file was auto-generated by Fern from our API Definition.

export interface RoleAssignmentDtoV1 {
    /** Represents a valid role. */
    role?: string | undefined;
    /** Represents user identifier across the system. */
    userId?: string | undefined;
    /** Represents workspace identifier across the system. */
    workspaceId?: string | undefined;
}
