// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Represents a scheduled assignment.
 */
export interface SchedulingAssignment {
    /** Indicates whether assignment is billable or not. */
    billable?: boolean | undefined;
    /** Represents a list of excluded days objects. */
    excludeDays?: ClockifyApi.SchedulingExcludeDay[] | undefined;
    /** Represents assignment total hours per day. */
    hoursPerDay?: number | undefined;
    /** Represents assignment identifier across the system. */
    id?: string | undefined;
    /** Indicates whether assignment should include non-working days or not. */
    includeNonWorkingDays?: boolean | undefined;
    /** Represents assignment note. */
    note?: string | undefined;
    period?: ClockifyApi.SchedulingDateRangeDto | undefined;
    /** Represents project identifier across the system. */
    projectId?: string | undefined;
    /** Indicates whether assignment is published or not. */
    published?: boolean | undefined;
    recurring?: ClockifyApi.RecurringAssignmentDto | undefined;
    /** Represents start time in hh:mm:ss format. */
    startTime?: string | undefined;
    /** Represents task identifier across the system. */
    taskId?: string | undefined;
    /** Represents user identifier across the system. */
    userId?: string | undefined;
    /** Represents workspace identifier across the system. */
    workspaceId?: string | undefined;
}
