// This file was auto-generated by Fern from our API Definition.

export const SchedulingExcludeDayType = {
    Weekend: "WEEKEND",
    Holiday: "HOLIDAY",
    TimeOff: "TIME_OFF",
} as const;
export type SchedulingExcludeDayType = (typeof SchedulingExcludeDayType)[keyof typeof SchedulingExcludeDayType];
