// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

export interface SharedReport {
    createdAt?: string | undefined;
    filter?: ClockifyApi.SharedReportFilter | undefined;
    id?: string | undefined;
    name?: string | undefined;
    public?: boolean | undefined;
    type?: SharedReport.Type | undefined;
    updatedAt?: string | undefined;
    url?: string | undefined;
    workspace?: SharedReport.Workspace | undefined;
}

export namespace SharedReport {
    export const Type = {
        Summary: "SUMMARY",
        Detailed: "DETAILED",
        Weekly: "WEEKLY",
        ExpenseDetailed: "EXPENSE_DETAILED",
        InvoiceTime: "INVOICE_TIME",
        KioskPinList: "KIOSK_PIN_LIST",
        AttendanceDetailed: "ATTENDANCE_DETAILED",
        AttendanceSummary: "ATTENDANCE_SUMMARY",
        AssignmentList: "ASSIGNMENT_LIST",
        AssignmentSchedule: "ASSIGNMENT_SCHEDULE",
        ApprovalDetailed: "APPROVAL_DETAILED",
        ApprovalSummary: "APPROVAL_SUMMARY",
        BalanceList: "BALANCE_LIST",
        InvoiceAmountList: "INVOICE_AMOUNT_LIST",
        InvoiceDetailed: "INVOICE_DETAILED",
        TimeoffDetailed: "TIMEOFF_DETAILED",
        TimeoffHoliday: "TIMEOFF_HOLIDAY",
        TimeoffBalance: "TIMEOFF_BALANCE",
        ExpenseSummary: "EXPENSE_SUMMARY",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];

    export interface Workspace {
        id?: string | undefined;
        name?: string | undefined;
        workspaceSettings?: ClockifyApi.WorkspaceSettings | undefined;
    }
}
