// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

export interface SubmitApprovalRequestRequest {
    period: ClockifyApi.ApprovalPeriod;
    /** Approval period start date in yyyy-MM-ddThh:mm:ssZ format. */
    periodStart: string;
}
