// This file was auto-generated by Fern from our API Definition.

/** Allowed summary grouping key. */
export const SummaryGroup = {
    Client: "CLIENT",
    Project: "PROJECT",
    User: "USER",
    Week: "WEEK",
    Date: "DATE",
    Month: "MONTH",
    Timeentry: "TIMEENTRY",
    Task: "TASK",
} as const;
export type SummaryGroup = (typeof SummaryGroup)[keyof typeof SummaryGroup];
