// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Summary report filter. Valid only on /reports/summary. At most three groups are allowed.
 */
export interface SummaryFilter {
    /** Summary report grouping levels. Maximum 3 groups. */
    groups: ClockifyApi.SummaryGroup[];
    /** Column used for sorting summary report rows. */
    sortColumn?: SummaryFilter.SortColumn | undefined;
    /** Summary chart type. */
    summaryChartType?: SummaryFilter.SummaryChartType | undefined;
}

export namespace SummaryFilter {
    /** Column used for sorting summary report rows. */
    export const SortColumn = {
        Group: "GROUP",
        Duration: "DURATION",
        Amount: "AMOUNT",
        Earned: "EARNED",
        Cost: "COST",
        Profit: "PROFIT",
    } as const;
    export type SortColumn = (typeof SortColumn)[keyof typeof SortColumn];
    /** Summary chart type. */
    export const SummaryChartType = {
        Billability: "BILLABILITY",
        Project: "PROJECT",
    } as const;
    export type SummaryChartType = (typeof SummaryChartType)[keyof typeof SummaryChartType];
}
