// This file was auto-generated by Fern from our API Definition.

export interface Tag {
    archived?: boolean | undefined;
    id?: string | undefined;
    name?: string | undefined;
    workspaceId?: string | undefined;
}
