// This file was auto-generated by Fern from our API Definition.

/**
 * Represents a tag object.
 */
export interface TagDto {
    /** Indicates whether tag is archived or not. */
    archived?: boolean | undefined;
    /** Represents tag identifier across the system. */
    id?: string | undefined;
    /** Represents tag name. */
    name?: string | undefined;
    /** Represents workspace identifier across the system. */
    workspaceId?: string | undefined;
}
