// This file was auto-generated by Fern from our API Definition.

/** Represents task status. */
export const TaskStatus = {
    Active: "ACTIVE",
    Done: "DONE",
    All: "ALL",
} as const;
export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus];
