// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Represents a task request object used when creating a project.
 */
export interface TaskRequest {
    assigneeId?: string | undefined;
    /** Represents list of assignee ids for the task. */
    assigneeIds?: string[] | undefined;
    /** Flag to set whether task is billable or not. */
    billable?: boolean | undefined;
    budgetEstimate?: number | undefined;
    costRate?: ClockifyApi.RateRequest | undefined;
    /** Represents a task duration estimate. */
    estimate?: string | undefined;
    hourlyRate?: ClockifyApi.RateRequest | undefined;
    /** Represents task identifier across the system. */
    id?: string | undefined;
    /** Represents task name. */
    name: string;
    /** Represents project identifier across the system. */
    projectId?: string | undefined;
    /** Represents task status. */
    status?: TaskRequest.Status | undefined;
    /** Represents list of user group ids for the task. */
    userGroupIds?: string[] | undefined;
}

export namespace TaskRequest {
    /** Represents task status. */
    export const Status = {
        Active: "ACTIVE",
        Done: "DONE",
        All: "ALL",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
