// This file was auto-generated by Fern from our API Definition.

/** Represents an invoice taxation type. */
export const TaxType = {
    Compound: "COMPOUND",
    Simple: "SIMPLE",
    None: "NONE",
} as const;
export type TaxType = (typeof TaxType)[keyof typeof TaxType];
