// This file was auto-generated by Fern from our API Definition.

/** Represents the time unit of the time off request. */
export const TimeUnit = {
    Days: "DAYS",
    Hours: "HOURS",
} as const;
export type TimeUnit = (typeof TimeUnit)[keyof typeof TimeUnit];
