// This file was auto-generated by Fern from our API Definition.

/**
 * Represents project time estimate request object.
 */
export interface TimeEstimateRequest {
    /** Flag whether to include only active or inactive estimates. */
    active?: boolean | undefined;
    /** Represents a time duration in ISO-8601 format. */
    estimate?: string | undefined;
    /** Flag whether to include non-billable expenses. */
    includeNonBillable?: boolean | undefined;
    resetOption?: TimeEstimateRequest.ResetOption | undefined;
    type?: TimeEstimateRequest.Type | undefined;
}

export namespace TimeEstimateRequest {
    export const ResetOption = {
        Weekly: "WEEKLY",
        Monthly: "MONTHLY",
        Yearly: "YEARLY",
    } as const;
    export type ResetOption = (typeof ResetOption)[keyof typeof ResetOption];
    export const Type = {
        Auto: "AUTO",
        Manual: "MANUAL",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
