// This file was auto-generated by Fern from our API Definition.

export const TimeEntryGroupType = {
    SingleItem: "SINGLE_ITEM",
    Grouped: "GROUPED",
    Detailed: "DETAILED",
} as const;
export type TimeEntryGroupType = (typeof TimeEntryGroupType)[keyof typeof TimeEntryGroupType];
