// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Represents the period of the time off request.
 */
export interface TimeOffRequestPeriodDto {
    halfDay?: boolean | undefined;
    halfDayHours?: ClockifyApi.Period | undefined;
    halfDayPeriod?: ClockifyApi.HalfDayPeriod | undefined;
    period?: ClockifyApi.Period | undefined;
}
