// This file was auto-generated by Fern from our API Definition.

/**
 * Represents a project time estimate object.
 */
export interface TimeEstimateDto {
    active?: boolean | undefined;
    /** Represents project duration in milliseconds or ISO-8601 duration. */
    estimate?: string | undefined;
    includeNonBillable?: boolean | undefined;
    resetOption?: TimeEstimateDto.ResetOption | undefined;
    type?: TimeEstimateDto.Type | undefined;
}

export namespace TimeEstimateDto {
    export const ResetOption = {
        Weekly: "WEEKLY",
        Monthly: "MONTHLY",
        Yearly: "YEARLY",
    } as const;
    export type ResetOption = (typeof ResetOption)[keyof typeof ResetOption];
    export const Type = {
        Auto: "AUTO",
        Manual: "MANUAL",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
