// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Represents a full time off request response.
 */
export interface TimeOffRequestFullV1Dto {
    /** Represents the time off balance. */
    balance?: number | undefined;
    /** Represents the balance difference. */
    balanceDiff?: number | undefined;
    /** Represents the date when time off request is created. It is in format YYYY-MM-DDTHH:MM:SS.ssssssZ */
    createdAt?: string | undefined;
    /** Represents time off requester identifier across the system. */
    id?: string | undefined;
    /** Represents the note of the time off request. */
    note?: string | undefined;
    /** Represents policy identifier across the system. */
    policyId?: string | undefined;
    /** Represents the policy name of the time off request. */
    policyName?: string | undefined;
    /** Represents requester user's id. */
    requesterUserId?: string | undefined;
    /** Represents requester user's username. */
    requesterUserName?: string | undefined;
    status?: ClockifyApi.TimeOffRequestStatus | undefined;
    timeOffPeriod?: ClockifyApi.TimeOffRequestPeriodDto | undefined;
    timeUnit?: ClockifyApi.TimeUnit | undefined;
    /** Represents user's email */
    userEmail?: string | undefined;
    /** Represents user identifier across the system. */
    userId?: string | undefined;
    /** Represents user's username. */
    userName?: string | undefined;
    /** Represents user's time zone */
    userTimeZone?: string | undefined;
    /** Represents workspace identifier across the system. */
    workspaceId?: string | undefined;
}
