// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

export interface TimeEntryDtoImplV1 {
    /** Indicates whether a time entry is billable. */
    billable?: boolean | undefined;
    /** Represents a list of custom field value objects. */
    customFieldValues?: ClockifyApi.CustomFieldValueDtoV1[] | undefined;
    /** Represents time entry description. */
    description?: string | undefined;
    /** Represents time entry identifier across the system. */
    id?: string | undefined;
    /** Represents whether time entry is locked for modification. */
    isLocked?: boolean | undefined;
    /** Represents kiosk identifier across the system. */
    kioskId?: string | undefined;
    /** Represents project identifier across the system. */
    projectId?: string | undefined;
    /** Represents a list of tag identifiers across the system. */
    tagIds?: string[] | undefined;
    /** Represents task identifier across the system. */
    taskId?: string | undefined;
    timeInterval?: ClockifyApi.TimeIntervalDtoV1 | undefined;
    /** Represents a time entry type enum. */
    type?: TimeEntryDtoImplV1.Type | undefined;
    /** Represents user identifier across the system. */
    userId?: string | undefined;
    /** Represents workspace identifier across the system. */
    workspaceId?: string | undefined;
}

export namespace TimeEntryDtoImplV1 {
    /** Represents a time entry type enum. */
    export const Type = {
        Regular: "REGULAR",
        Break: "BREAK",
        Holiday: "HOLIDAY",
        TimeOff: "TIME_OFF",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
