// This file was auto-generated by Fern from our API Definition.

export interface TimeEntryCreate {
    billable?: boolean | undefined;
    customFields?: TimeEntryCreate.CustomFields.Item[] | undefined;
    description?: string | undefined;
    /** Omit to start a running timer */
    end?: string | undefined;
    projectId?: string | undefined;
    /** Required ISO 8601 */
    start: string;
    tagIds?: string[] | undefined;
    taskId?: string | undefined;
    type?: TimeEntryCreate.Type | undefined;
}

export namespace TimeEntryCreate {
    export type CustomFields = CustomFields.Item[];

    export namespace CustomFields {
        export interface Item {
            customFieldId?: string | undefined;
            sourceType?: Item.SourceType | undefined;
            /** Polymorphic — string/number/array depending on custom-field type */
            value?: unknown | undefined;
        }

        export namespace Item {
            export const SourceType = {
                Workspace: "WORKSPACE",
                Project: "PROJECT",
            } as const;
            export type SourceType = (typeof SourceType)[keyof typeof SourceType];
        }
    }

    export const Type = {
        Regular: "REGULAR",
        Break: "BREAK",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
