// This file was auto-generated by Fern from our API Definition.

export interface TimeEntriesCustomFieldValueDto {
    customFieldId?: string | undefined;
    name?: string | undefined;
    timeEntryId?: string | undefined;
    type?: TimeEntriesCustomFieldValueDto.Type | undefined;
    value?: (string | null) | undefined;
}

export namespace TimeEntriesCustomFieldValueDto {
    export const Type = {
        Workspace: "WORKSPACE",
        Project: "PROJECT",
        Timeentry: "TIMEENTRY",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
