// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

export interface TimeEntriesTimeEntry {
    billable?: boolean | undefined;
    customFieldValues?: ClockifyApi.TimeEntriesCustomFieldValueDto[] | undefined;
    description?: string | undefined;
    id?: string | undefined;
    isLocked?: boolean | undefined;
    projectId?: (string | null) | undefined;
    tagIds?: (string[] | null) | undefined;
    taskId?: (string | null) | undefined;
    timeInterval?: ClockifyApi.TimeEntriesTimeIntervalDto | undefined;
    type?: TimeEntriesTimeEntry.Type | undefined;
    userId?: string | undefined;
    workspaceId?: string | undefined;
}

export namespace TimeEntriesTimeEntry {
    export const Type = {
        Regular: "REGULAR",
        Break: "BREAK",
        Holiday: "HOLIDAY",
        TimeOff: "TIME_OFF",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
