// This file was auto-generated by Fern from our API Definition.

export const TimeEntryPrimaryGroupBy = {
    User: "USER",
    Project: "PROJECT",
    Date: "DATE",
} as const;
export type TimeEntryPrimaryGroupBy = (typeof TimeEntryPrimaryGroupBy)[keyof typeof TimeEntryPrimaryGroupBy];
