// This file was auto-generated by Fern from our API Definition.

/**
 * Represents total hours per day object.
 */
export interface TotalsPerDayDto {
    date?: string | undefined;
    totalHours?: number | undefined;
}
