// This file was auto-generated by Fern from our API Definition.

export interface UpsertUserCustomFieldRequest {
    /** Represents custom field identifier across the system. */
    customFieldId: string;
    /** Represents custom field value. */
    value?: (unknown | null) | undefined;
}
