// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Represents a user.
 */
export interface UserDtoV1 {
    /** Represents user's active workspace identifier across the system. */
    activeWorkspace?: string | undefined;
    /** Represents a list of value objects for user’s custom fields. */
    customFields?: ClockifyApi.UserCustomFieldValueDtoV1[] | undefined;
    /** Represents user default workspace identifier across the system. */
    defaultWorkspace?: string | undefined;
    /** Represents email address of the user. */
    email?: string | undefined;
    /** Represents user identifier across the system. */
    id?: string | undefined;
    /** Represents a list of membership objects. */
    memberships?: ClockifyApi.UsersMembershipDtoV1[] | undefined;
    /** Represents name of the user. */
    name?: string | undefined;
    /** Represents profile image path of the user. */
    profilePicture?: string | undefined;
    settings?: ClockifyApi.UserSettingsDtoV1 | undefined;
    status?: ClockifyApi.AccountStatus | undefined;
    /** Included when user responses request role details; shape varies by workspace role surface. */
    roles?: Record<string, unknown>[] | undefined;
}
