// This file was auto-generated by Fern from our API Definition.

/**
 * Request body for creating or updating a user group.
 */
export interface UserGroupRequest {
    /** Represents a user group name. */
    name: string;
}
