// This file was auto-generated by Fern from our API Definition.

/**
 * Represents a redacted user object.
 */
export interface UserRedactedDtoV1 {
    /** Represents a user identifier across the system. */
    id?: string | undefined;
    /** Represents a user name. */
    name?: string | undefined;
}
