// This file was auto-generated by Fern from our API Definition.

/** Represents a zero-value invoice field that will be visible. */
export const VisibleZeroFieldsInvoice = {
    Tax: "TAX",
    Tax2: "TAX_2",
    Discount: "DISCOUNT",
} as const;
export type VisibleZeroFieldsInvoice = (typeof VisibleZeroFieldsInvoice)[keyof typeof VisibleZeroFieldsInvoice];
