// This file was auto-generated by Fern from our API Definition.

export interface WebhooksClockifyError {
    /** Observed 501 for validation, 3000 for unsupported method. */
    code?: number | undefined;
    message?: string | undefined;
}
