// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * For USER_EMAIL_CHANGED and USER_UPDATED, live Clockify requires triggerSourceType USER_ID and a nonempty triggerSource user id.
 */
export interface WebhookRequest {
    /** Represents a webhook name. */
    name: string;
    /**
     * Represents a list of trigger sources.
     * USER_EMAIL_CHANGED and USER_UPDATED require at least one user id.
     */
    triggerSource: string[];
    /** USER_EMAIL_CHANGED and USER_UPDATED require USER_ID. */
    triggerSourceType: ClockifyApi.WebhookEventTriggerSourceType;
    /** Represents a webhook target url. */
    url: string;
    webhookEvent: ClockifyApi.WebhookEventType;
}
