// This file was auto-generated by Fern from our API Definition.

export interface WebhooksErrorEnvelope {
    /** Clockify domain code, NOT HTTP status. Mostly 501 even when HTTP is 400. */
    code?: number | undefined;
    message?: string | undefined;
}
