// This file was auto-generated by Fern from our API Definition.

export const WebhookType = {
    UserCreated: "USER_CREATED",
    System: "SYSTEM",
    Addon: "ADDON",
} as const;
export type WebhookType = (typeof WebhookType)[keyof typeof WebhookType];
