// This file was auto-generated by Fern from our API Definition.

export interface WebhookLogDtoV1 {
    /** Represents log identifier across the system. */
    id?: string | undefined;
    /** Represents request body. */
    requestBody?: string | undefined;
    /** Represents date and time of response. */
    respondedAt?: string | undefined;
    /** Represents response body. */
    responseBody?: string | undefined;
    /** Represents response status code. */
    statusCode?: number | undefined;
    /** Represents webhook event status identifier across the system. */
    webhookEventStatusId?: string | undefined;
    /** Represents webhook identifier across the system. */
    webhookId?: string | undefined;
}
