// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Weekly report response.
 */
export interface WeeklyReportResponse {
    /** Indicates whether the time entry report is in decimal format. */
    decimalFormat?: boolean | undefined;
    /** List of groups. */
    groupOne?: ClockifyApi.GroupOneDto[] | undefined;
    /** Indicates whether the report includes users without time. */
    includeUsersWithoutTime?: boolean | undefined;
    /** List of totals. */
    totals?: ClockifyApi.TimeEntryReportTotals[] | undefined;
    /** Daily totals. */
    totalsByDay?: ClockifyApi.DailyTotalDto[] | undefined;
    /** Indicates whether time is tracked down to seconds. */
    trackTimeDownToSeconds?: boolean | undefined;
    /** Users without time. */
    usersWithoutTime?: ClockifyApi.UserDto[] | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
