// This file was auto-generated by Fern from our API Definition.

/**
 * Represents the workspace subdomain.
 */
export interface WorkspaceSubdomainDtoV1 {
    /** Indicates whether subdomain is enabled on workspace. */
    enabled?: boolean | undefined;
    /** Represents subdomain name. */
    name?: string | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
