// This file was auto-generated by Fern from our API Definition.

import type * as ClockifyApi from "../index.js";

/**
 * Workspace object.
 */
export interface Workspace {
    /** Represents the Cake organization identifier across the system. */
    cakeOrganizationId?: string | undefined;
    costRate?: ClockifyApi.WorkspacesRateDtoV1 | undefined;
    currencies?: ClockifyApi.CurrencyWithDefaultInfoDtoV1[] | undefined;
    /** Represents a feature plan type enum. */
    featureSubscriptionType?: string | undefined;
    /** Represents a list of features. */
    features?: ClockifyApi.WorkspacesFeature[] | undefined;
    hourlyRate?: ClockifyApi.WorkspacesRateDtoV1 | undefined;
    /** Represents workspace identifier across the system. */
    id?: string | undefined;
    /** Represents an image url. */
    imageUrl?: string | undefined;
    memberships?: ClockifyApi.WorkspacesMembershipDtoV1[] | undefined;
    /** Represents workspace name. */
    name?: string | undefined;
    subdomain?: ClockifyApi.WorkspaceSubdomainDtoV1 | undefined;
    workspaceSettings?: ClockifyApi.WorkspaceSettingsDtoV1 | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
