// This file was auto-generated by Fern from our API Definition.

/**
 * Represents hourly rate object.
 */
export interface WorkspacesRateDtoV1 {
    /** Represents an amount as integer. */
    amount?: number | undefined;
    /** Represents a currency. */
    currency?: string | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
